### ISSUE TITLE
Implement an expand/collapse list for ``politician_detail.html``

### ISSUE THREAD

**Issue by ghost** [openpolis/open_municipio#110]
Page `politician_detail.html` needs an expand/collapse list of key votations, as explained here: https://github.com/openpolis/open_municipio/commit/675b2c6e91443163d2dc374cdb726904dab39eb1

I think this could be achieved via Javascript.

**Comment by lorenzo-pasa** [comment]
This feature must be implemented also for the "Atti su cui lavora" section of the `politician_detail.html` template.

**Comment by guglielmo** [comment]
The links are not expandable sections, but simple links, that bring to a pre-filtered result set of the general search interface.
