### ISSUE TITLE
Tagging an act should bind tags and categories

### ISSUE THREAD

**Issue by guglielmo** [openpolis/open_municipio#131]
When tagging an act with the frontend interface, the categories and tags should be binded together directly, so that the Topics page can be built correctly.

For a  `category` and a list of `tags`:

```
# associate tags with the category
category.tag_set.add(*tags)
```

**Comment by joke2k** [comment]
fixed in _new_tagging_ signal:

https://github.com/openpolis/open_municipio/blob/dev/open_municipio/taxonomy/models.py#L127

now we have to find a way to remove this association...
