### ISSUE TITLE
Remove ``ChargeXRef`` element from OM-XML schema

### ISSUE THREAD

**Issue by seldon** [openpolis/open_municipio#140]

**Comment by seldon** [comment]
In the data-import domain, there are contexts where we have to identify the politician who is performing a certain
action (e.g. issuing a vote during a ballot, subscribing an act, and so on).  OpenMunicipio already assigns a unique ID
to every politician within its DB, but there is a problem: actual data coming from municipalities generally use a
different set of (internal) IDs for referring to politicians (counselors, assessors, ..).  So we have to devise a mechanism to properly map these different ID sistems.

Currently, we use a `ChargeXRef` element and _XLink_ syntax to implement this mapping at the XML level; however, for convenience reasons, we have decided to switch to a (Django) model-based tracking system; this way that mapping can be managed via the web UI, and the associated housekeeping work may be delegated to editors.

As a consequence, both `ChargeXRef` elements (that under the `ChargeVote` element and that under the
`ActSubscribers` element) are no longer necessary, and should be removed from the XML Schema Definition and sample XML instances.  The information carried by these element should be replaced by a `chargeID` attribute on their parent element.

**Comment by fspegni** [comment]
added an element ChargeRef for those contexts where a single chargeID attribute was not enough (for example in element &lt;ActTargets&gt; a multitude of charges are referenced).
