### ISSUE TITLE
Implement a dashboard for editors 

### ISSUE THREAD

**Issue by seldon** [openpolis/open_municipio#142]
Editor users should have easy access to every information they need to perform their work, in particular:
- acts that have recently been imported into a given instance of OpenMunicipio (so they can tag & title them)
- notifications concerning issues related with data-import tasks (as logged by import scripts)

**Comment by seldon** [comment]
Some implementation-related considerations:
- the _queue_ of "to-review" acts may be implemented with a dedicated DB table
- dashboard-displayed notifications may be generated by leveraging Python built-in logging framework (stdlib `logging` module) + Django logging support

**Comment by guglielmo** [comment]
This has been implemented as a notification email, sent to all interested party. It's going to be released in 0.2.2
