### ISSUE TITLE
Add support for politician's speeches

### ISSUE THREAD

**Issue by seldon** [openpolis/open_municipio#164]
Speeches made by politicians during a Council/Commission sitting may be very interesting pieces of information from a citizen's perspective.

In order to track (and, subsequently, display) these contents within OpenMunicipio, first of all we have to extend our data model, adding a `Speech` model class.

This model needs to capture the following pieces of information:
- who was the speaker (a politician)
- a short description of the speech's content
- when the speech started
- when the speech ended
- what was the context where the speech took place (a Council sitting, a Commission sitting, etc.)
- the serial number of the speech (within a given agenda item)
- an (optional) audio file recording the speech

**Comment by scaloni** [comment]
A speech should have also the following optional information:
- one or more tags
- a title

**Comment by scaloni** [comment]
The context of a speech could be as flexible as possible; for example any of the following:
- an URL, as in openpolitici (http://politici.openpolis.it)
- an OM Event
- an OM EventAct

**Comment by scaloni** [comment]
Please consider to join speeches to Sittings instead of EventActs.
