### ISSUE TITLE
Pagina politici: data cambio gruppo

### ISSUE THREAD

**Issue by filipic** [openpolis/open_municipio#180]
in  http://udine.staging.openmunicipio.it/people/ nel blocco "ultimi cambiamenti di gruppo":
- la data va messa in italiano
- controllare esattezza dati, l'ultimo cambio risulta al 29 aprile 2009, in tre anni e mezzo nessuno ha cambiato gruppo?

**Comment by guglielmo** [comment]
Ok, la data è in italiano, le date erano sbagliate, venivano messe le date di inizio carriera in quanto consigliere e non quelle del gruppo. Considerando la data di inizio dell'incarico corrente, l'ultimo cambio è avvenuto il 30 novembre 2011.
C'è un documento da cui abbiamo preso i dati, che però potrebbe essere aggiornato alla prima metà del 2012.
