### ISSUE TITLE
Pagina politici: non funziona monitora - non ci sono le ultime news

### ISSUE THREAD

**Issue by filipic** [openpolis/open_municipio#181]
in http://udine.staging.openmunicipio.it/people/;
- non funziona la funzione monitora accanto al nome di un politico
- non ci sono le ultime sui politici (spalla destra)

**Comment by guglielmo** [comment]
La funzione di monitoraggio funziona solo quando si è loggati con un utente che ha un profilo.

Gli utenti che si registrano e quelli _demo_ hanno un profilo.

Le news sui politici sono implementate.
