### ISSUE TITLE
Paginadi un politico: varie

### ISSUE THREAD

**Issue by filipic** [openpolis/open_municipio#183]
nella pagina di un politico, ad esempio:
http://udine.staging.openmunicipio.it/people/alberto-bertossi-1965-09-17/
- Inserire gruppo attuale di appartenenza (indicare se capogruppo) con storico dei cambi gruppi
- indicare le commissioni di cui fa parte (indicare se presidente)
- Negli incarichi istituzionali, mettere le voci in italiano (attualmente c'è Counselor)
- non ci sono le presenze/assenze
- non ci sono i voti chiave
- alla fine di "atti su cui lavora" il link a "Vedi tutti gli atti su cui lavora" non funziona
- il "condividi" in fondo alla pagina non funziona (vale per tutte le pagine)
- non funziona la funzione Monitora
- Non capisco se "argomenti di cui si occupa" è ben calcolato
- il "leggi tutte" in fondo alle news sul politico non funziona

**Comment by guglielmo** [comment]
Il malfunzionamento dei link "vai a tutti gli atti, vai a tutti i voti chiave" è affrontato in #200.
