### ISSUE TITLE
Caricare le foto dei politici

### ISSUE THREAD

**Issue by filipic** [openpolis/open_municipio#184]
Non sono presenti le foto dei politici. Occorre caricarle per poterne testare la visualizzazione

**Comment by strk** [comment]
Guglielmo: se scrivi "Closes #184" nel commit log il ticket si chiude automaticamente _e_ rimane un riferimento al commit che risolve il problema. Molto utile, in generale.

**Comment by guglielmo** [comment]
Ciao strk,
ce lo sapevo, molto comodo ...
Sto solo chiudendo a mano dei ticket, riorganizzandoli, e aggiungendo una serie di ticket da todo list che avevo sparse in giro,
in modo che ricominciamo a usare questo come fonte unica delle cose da fare.

grazie delle osservazioni (e dell'incoraggiamento)

:-)

Il giorno 11/dic/2012, alle ore 17:57, strk notifications@github.com ha scritto:
