### ISSUE TITLE
Pagina di un argomento

### ISSUE THREAD

**Issue by filipic** [openpolis/open_municipio#185]
nella pagina di un singolo argomento:
http://udine.staging.openmunicipio.it/categories/mobilita/
- il calendario mostra eventi reali?
- non funziona il monitora
- cambiare la scritta "Cittadini che monitorano category" in "Cittadini che monitorano l'argomento"
- è finta la tabella "Atti che trattano di Mobilità". Va riempita di numeri veri, ognuno linkato al motore di ricerca

**Comment by guglielmo** [comment]
Il calendario è finto, ma in realtà come va costruito?
Gli eventi hanno titolo descrizione e qualche volta un atto.
L'unico aggancio per arrivare ad argomenti e categorie è l'atto, che però non c'è sempre.
Forse bisogna legare Event agli argomenti.

**Comment by guglielmo** [comment]
Per il calendario, veder il #205. Tutto il reso è chiuso.
