### ISSUE TITLE
Oscuramento dati personali [bloccante]

### ISSUE THREAD

**Issue by vittorioa** [openpolis/open_municipio#199]
La responsabilità penale e civile della violazione delle norme sulla privacy è di chi pubblica il dato (depp - informaetica) e non della fonte (Comune). Occorre quindi definire procedura e madalità di oscuramento.
Sia preventivo / redazionale sia successivo, su richiesta eventuale degli interessati.

**Comment by guglielmo** [comment]
Siamo in grado di intervenire direttamente nel DB, via interfaccia web, per rimuovere questo tipo di informazioni.

Le informazioni nel titolo e nella eventuale descrizione sono indicizzate, mentre quelle negli allegati, no. Per cui il ticket si può chiudere, stando attenti che quando si indicizza il contenuto degli allegati, si parta dai campi del DB e non dal testo convertito del doc (o del pdf).
