### ISSUE TITLE
Add relation data between Events and Acts

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#212]
An event (events.Event) must be related to many acts, and this relation must have some associated data.
The association data includes an integer called priority, which indicates the position of act in the order of discussion.

**Comment by fspegni** [comment]
Relation EventAct created. Some interface issues:
- the priority field must be read-only and computed depending on the position of the Act in the list
- it should be possible to move up/down an Act within the same EventAct relation (use up/down arrows)
- when an Act is removed in the interface, the order must be recomputed (no "empty" bubbles in the EventAct ordering ...)

**Comment by scaloni** [comment]
Rimane da fare l'adattamento della UI

**Comment by fspegni** [comment]
adattamento gia` presente: cliccando sull'evento, appare il popup che descrive l'evento e fa la lista degli atti collegati tramite EventAct (linkabili)
