### ISSUE TITLE
Voti ribelli

### ISSUE THREAD

**Issue by vittorioa** [openpolis/open_municipio#213]
Inserire i voti ribelli nella pagina del poltico. in pagina si mostrano gli ultimi tre voti ribelli. Il vedi tutti innesca ricerca del motore che fornisce la lista di tutti i voti ribelli del politico. Stesso comportamento (link a tutti i voti ribelli) per il numero dei voti ribelli presente nella lista dei consglieri in Consiglio e in Gruppi.

**Comment by scaloni** [comment]
Chiuso in dev-senigallia
