### ISSUE TITLE
Link "Il progetto e come aderirvi" errato

### ISSUE THREAD

**Issue by strk** [openpolis/open_municipio#214]
Dalla homepage www.openmunicipio.it il link in basso a sinistra "Il progetto e come aderirvi" punta ad un indirizzo inesistente: http://www.openmunicipio.it/project.html

**Comment by strk** [comment]
Quando avete tempo: una ricerca sul perche' questo ticket e' importante :)
http://www.slideshare.net/Eldarion/motivation-in-floss-communities

**Comment by joke2k** [comment]
Ciao, grazie per la segnalazione.
Effettivamente la pagina ha cambiato indirizzo, ma sul sito è stato aggiornato correttamente.
Per evitare problemi metteremo una pagina di redirect.

**Comment by strk** [comment]
Grazie, confermo che ora funziona (evitando le cache). Ottima idea mettere un redirect.
Keep up the good work!
