### ISSUE TITLE
Problemi con registrazione al sito

### ISSUE THREAD

**Issue by flaviab** [openpolis/open_municipio#219]
Dal nostro account twitter:
Francesco Contin ‏@FrenchContin
Buonasera assessore @coppolapaolo, io vorrei monitorarla su #openudine ma non riesco a registrarmi al sito. Come si fa? : ) #smartcitizens

9 Dic coppolapaolo ‏@coppolapaolo
@FrenchContin in effetti qualche problema con la piattaforma c'e'. Lo segnaliamo a @openpolis Grazie! :-)
5:47 AM - 9 Dic 12

9 Dic Elisabetta Paviotti ‏@BettyPav
@coppolapaolo @FrenchContin @openpolis pure io avevo provato ad iscrivermi (tramite gmail), ma

**Comment by strk** [comment]
Stesso problema per me:

in fase di login, dopo aver ritirato  
le informazioni da google-oauth2 e aver checckato il necessario  
(ho letto e condivido etc.etc) e cliccato su 'Invia'  
la pagina rimane li' dove si trova (nella form) e mi lascia  
quindi perplesso (sono loggato ? non sono loggato ?).  
A giudicare dall'indicatore in alto a destra NON sono loggato  
(dice ancora "Per partecipare o registrarti, ENTRA").

**Comment by guglielmo** [comment]
Il problema dovrebbe essere risolto
