### ISSUE TITLE
Errore nella visualizzazione della percentuale di ribellione

### ISSUE THREAD

**Issue by seldon** [openpolis/open_municipio#226]
Nelle pagine che dettagliano l'attività dei politici (`people/*`), c'è una sezione dal titolo "Voti ribelli", che riportati i voti ribelli espressi dal politico in questione, sia in valore assoluto che in percentuale sulle votazioni totali in cui il politico era presente.  La percentuale viene riportata con 1 cifra significativa, ma è arrotondata (o troncata?) in modo errato.  Ad esempio, in [questa pagina](http://udine.openmunicipio.it/people/fabrizio-anzolini-1983-07-21/) la percentuale risulta 0.0%, mentre i voti ribelli sono !=0 (attualmente, 5).

**Comment by ghost** [comment]
Visti i numeri delle votazioni riportate sopra (mi riferisco alla pagina citata), mi pare plausibile si tratti di un problema di troncamento, che fa perdere delle cifre significative dello sviluppo decimale.

La riga mi pare sia questa:
https://github.com/openpolis/open_municipio/blob/dev/open_municipio/people/views.py#L323

È probabile che anche usando **due** cifre significative ci siano dei casi degeneri in cui risulta una percentuale nulla "0.00%", a fronte di un numero assoluto non nullo. Forse varrebbe la pena agire a livello di template, omettendo la pecentuale quando è zero o sostituendola con un "~0%".
