### ISSUE TITLE
Errore dopo caricamento immagine utente

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#249]
Dalla pagina del profilo utente, il tentativo di caricare una immagine produce la schermata di "un errore imprevisto sui nostri server".
L'utente si era registrato via Facebook.

![om-udine-user-edit](https://f.cloud.github.com/assets/799159/111317/268825a0-6af1-11e2-80df-9d7855023bca.jpg)
![om-udine-user-edit-error](https://f.cloud.github.com/assets/799159/111318/2ae014e6-6af1-11e2-96b1-a6681247fab8.jpg)

**Comment by joke2k** [comment]
Il problema si presenta anche se ci si autentica con twitter.
In locale, facebook non mi fa autentificare rispondendomi sempre "Si è verificato un errore. Riprova più tardi.", mentre twitter mi autorizza, e riesco anche a fare l'upload dell'avatar.
Che ci sia qualche problema nella configurazione sul server di produzione?

Si c'è un problema di permessi in scrittura sul server. (django non può scrivere in media/)
