### ISSUE TITLE
Aggiungere colonna "Presente non votante"

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#250]
Nella pagina di dettaglio di una votazione (per esempio /votations/67/) è necessario distinguere l'assenza durante il voto (cioè la scheda del consigliere non è inserita nel lettore) dalla presenza senza espressione di voto (scheda inserita ma nessun tasto di voto premuto: ne favorevole, ne contrario, ne astenuto).

**Comment by fspegni** [comment]
analizzare cosa avviene. per ora il valore di votazione che indica il "presente non votante" è PRE, che però sembra scartato dai valori di votazioni utili. 
- verificare cosa accade quando è presente un PRE tra i valori di votazione ricevuta

nota: evitare di creare una nuova colonna "presente non votante", perché renderebbe l'interfaccia meno leggibile

**Comment by scaloni** [comment]
La distinzione viene evidenziata nella colonna degli astenuti, mediante diverse indicazioni ("Non Votante" in alternativa ad "Astenuto"), eventualmente con colori leggermente diversi.
