### ISSUE TITLE
Impedire impostazione nickname/nome-cognome

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#253]
Al momento la pagina /users/profile/edit/ consente all'utente di scegliere se mostrarsi esclusivamente con il proprio nome utente (nickname) oppure con il Nome Cognome.
Deve essere possibile configurare un'istanza OM in modo tale da non permettere all'utente di impostare tale preferenza, che dunque potrà essere decisa centralmente da OM per tutti gli utenti.

**Comment by fspegni** [comment]
risolto: definita form personalizzata SenigalliaUserRegistrationForm(UserRegistrationForm) che setta il campo non desiderato come HiddenField

**Comment by scaloni** [comment]
Al momento la pagina http://senigallia.openmunicipio.it/users/profile/edit/ di un utente registrato presenta ancora l'opzione "Mostra il mio nickname al posto del mio nome reale"

**Comment by fspegni** [comment]
se l'utente si logga come utente di test, la url di edit profile da` errore
