### ISSUE TITLE
Migliorare la maschera di input dell'orario

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#266]
Con lo scopo di limitare al massimo gli errori:
- evitare che l'utente possa digitare il separatore
- eventualmente inserire dei controlli per aumentare/diminuire le ore o i secondi di una unità

**Comment by fspegni** [comment]
usare SplitTimeField e SplitTimeWidget come da questo snippet: http://djangosnippets.org/snippets/590/
