### ISSUE TITLE
Affinare modalità di ricerca atto

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#267]
Laddove nell'interfaccia di admin si debba scegliere un atto per inserirlo in un campo di una maschera, migliorare l'esperienza utente:
- limitando la larghezza della select
- eventualmente prevedere dei controlli per filtrare gli atti

**Comment by fspegni** [comment]
al momento la soluzione migliore sembra essere usare l'attributo raw_id_fields (fa comparire una lente di ingrandimento per cercare un atto).

ora viene utilizzato anche negli Speech
