### ISSUE TITLE
Bug in custom forms and inlines

### ISSUE THREAD

**Issue by fspegni** [openpolis/open_municipio#274]
In order to add an inline form within a "regular" admin form, it is required to define a change_view method within the ModelAdmin extension (see ActAdmin.change_view).

such method should call at some point super(...).change_view(...) passing the proper parameters. see

https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.change_view

in ActAdmin.change_view the form_url is forgotten (this causes saving an Act from admin interface to generate a RuntimeError, and if you inspect the page when editing an Act, you will see "<form ... action='None' ..." which causes the error.

assign to guglielmo because this concerns a core feature of the project

**Comment by fspegni** [comment]
i think it should be fixed like this:

class ActAdmin(...):
...
    def change_view(self, request, object_id, form_url='', extra_context=None):
...
        super(ActAdmin,self).change_view(request, object_id, form_url, extra_content)

**Comment by guglielmo** [comment]
This has been closed in commit 66655e0d407a9bc91c0d11099a7ccce122a14b72.
