### ISSUE TITLE
Gestione ex

### ISSUE THREAD

**Issue by flaviab** [openpolis/open_municipio#286]
"Si potrebbe pensare ad una eventuale gestione dei Consiglieri dimessi o di precedenti legislature, in modo tale che il cittadino possa “indagare” sul lavoro effettuato dal Consigliere non più in carico, comprese le sue presenze alle votazioni"

**Comment by scaloni** [comment]
La funzionalità sarà necessaria entro il 2015 a Senigallia

**Comment by scaloni** [comment]
La funzionalità è introdotta in dev (vedi http://senigallia.openmunicipio.it/people/charge/) e migliorata in dev-senigallia
