### ISSUE TITLE
Filtra atti per mese

### ISSUE THREAD

**Issue by flaviab** [openpolis/open_municipio#287]
Sarebbe utile permettere di filtrare gli atti (oltre che per anno) anche per mese.

**Comment by fspegni** [comment]
scusate, state parlando del frontend (la ricerca faccettata) o del backend (i filtri lato admin)? se vi riferite al backend, ho inserito dei filtri nella branch dev_senigallia

**Comment by scaloni** [comment]
sarebbe utile anche da frontend

**Comment by scaloni** [comment]
Duplicato in #435
