### ISSUE TITLE
problema con voti

### ISSUE THREAD

**Issue by flaviab** [openpolis/open_municipio#290]
la Segreteria sta effettuando la mappatura votazioni atti e ha notato che manca l'atto
2011/4913/00006. In effetti questo non è presente sul portale, ma lo trovo tra il materiale
che vi avevo passato l'ultima volta. Provate a verificare e capire se questo è successo
anche per qualche altro atto.

**Comment by guglielmo** [comment]
L'errore è dovuto a un errore di sintassi dell'XML fornito dal cliente.

**Comment by guglielmo** [comment]
Per importarlo correttamente, bisogna aumentare la dimensione massima del titolo degli allegati,
in staging è importato, quando le modifiche saranno deployate in produzione,
verrà aggiunto regolarmente.

http://udine.staging.openmunicipio.it/acts/deliberations/3552/
