### ISSUE TITLE
Personalizzare loghi e link del Comune

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#291]
Aggiornare:
- il logo (+ link) in alto a destra
- il logo (+ link) al centro del footer

**Comment by fspegni** [comment]
risolto

**Comment by fspegni** [comment]
andrebbe sostituito il link al sito istituzionale del comune (ora manda al sito di udine). v. in basso ad ogni pagina

**Comment by scaloni** [comment]
Salvo avviso contrario, mettiamo questo allegato (è un RGB con canale alfa).
![senigallia-logo-sole](https://f.cloud.github.com/assets/799159/639882/fd311d72-d2df-11e2-993d-b8845b1f13d1.png)

**Comment by scaloni** [comment]
![footer-logo-senigallia](https://f.cloud.github.com/assets/799159/644922/20025910-d399-11e2-88c1-ff2e57de41b6.png)
