### ISSUE TITLE
Gestione più robusta per i campi SeqOrder

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#294]
I campi che contengono numero sequenziali (Seq Order) dovrebbero essere gestiti dall'interfaccia di admin con appositi controlli (freccine, auto-incremento) in modo da garantirne la continuità, evitare doppioni o salti nell'ordinamento.

**Comment by fspegni** [comment]
risolto per quelli che hanno un campo seq_order gestito tramite form inline. da risolvere per modelli (come speech) che hanno campo seq_order non gestito tramite form inlines

**Comment by scaloni** [comment]
Da admin un SittingItem gestirà i relativi Speech in modalità inline. Ciascuno speech inline avrà alcuni campi (quelli mandatari e/o inseribili inline) e in più un link alla scheda completa.
