### ISSUE TITLE
Campi Raw Id più leggibili

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#302]
I campi di tipo Raw id dovrebbero essere popolati con informazioni più significative (per esempio nei SittingItem mettere Idnum anziché Id)

**Comment by fspegni** [comment]
forse puo` fare al caso nostro:
1) https://code.djangoproject.com/ticket/7028
2) http://djangosnippets.org/snippets/2217/

qui un esempio di uso di (2)
https://gist.github.com/EmilStenstrom/4761449

**Comment by fspegni** [comment]
al momento, il modo piu`"semplice" e` usare la patch al punto (2) di cui sopra:
- scaricare la versione per django 1.4.5 (perche` usiamo questa versione) nel file : patch7028-1.4.5.patch
- cd $VIRTUAL_ENV/lib/python2.6/site-packages/django
- patch --dry-run -p2 < patch7028-1.4.5.patch
- se non da` errori (a parte quelli per i file della cartella regressiontests, che non abbiamo), rieseguire senza "--dry-run"
- sudo apache2ctl stop
- esegui django-admin.py collectstatic (nel virtualenv)
- sudo apache2ctl start
