### ISSUE TITLE
Estendere filtri su campo Raw Id degli atti

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#307]
Aggiungere i filtri per:
- anno
- tipo di atto

**Comment by fspegni** [comment]
aggiunto in commit: https://github.com/openpolis/open_municipio/commit/02b2fe27bef377f397ca0bd98374beeeb53aa0ad

il filtro ActByTypeFilterSpec (in acts/filters.py) non viene pero` usato dall'admin di open_municipio. viene invece usata dall'admin di open_senigallia

**Comment by scaloni** [comment]
Il disallineamento tra open_municipio e open_senigallia è dovuto al fatto che il commit riguarda per ora il branch dev_senigallia?
Questa modifica potrà essere megiata sul branch comune (dev)?

**Comment by fspegni** [comment]
no, il motivo e`piu` "semplice":
- se aggiungo ActByTypeFilterSpec (filtro degli atti per tipo di atti) nella vista ActAdmin, quello stesso filtro viene ereditato dalle admin-view di tutti gli atti (DeliberationAdmin, CGDeliberationAdmin, ...) perche` queste estendono ActAdmin. per capire: in questo modo chi vuole vedere le delibere, troverebbe anche il filtro per tipo di atto (che non ha senso)
- su open_senigallia, invece, abbiamo SenigalliaActAdmin che viene usata al posto di ActAdmin: se aggiungo il filstro su SenigalliaActAdmin, le altre admin-view (continuando ad estendere ActAdmin, e non SenigalliaActAdmin) non verrebbero "intaccate" dal filtro

Per concludere: la soluzione ideale sarebbe, sotto OpenMunicipio, creare una classe AllActsAdmin (dico un nome a caso) che estenda ActAdmin, e poi specificare:

admin.site.register(Act,AllActAdmin)

al posto dell'attuale:

admin.site.register(Act,ActAdmin)

cosi`facendo, il filstro per tipo di atto verrebbe aggiunto ad AllActAdmin (anziche` ad ActAdmin), e tutte le altre admin-view (che continuano ad estendere ActAdmin) non sarebbero a conoscenza di questo filtro.

Poiche`e` una modifica abbastanza "profonda" all'interfaccia di admin, direi che andrebbe discussa con @Guglielmo.
