### ISSUE TITLE
Spazio bianco anomalo nella pagina di un SittingItem

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#311]
Nella pagina di un SittingItem (per esempio sittings/item/2) eliminare lo spazio bianco iniziale, che appare dipendere dalla lunghezza della lista affiancata destra, contenete i titoli degli atti collegati.
Inoltre controllare l'allineamento verticale dei vari speech. Ora appaiono affiancati anche in orizzontale (si veda immagine allegata)
![open municipio - consiglio](https://f.cloud.github.com/assets/799159/505593/7e43f4c8-bd2f-11e2-958b-d7ddcefee53f.png)

**Comment by fspegni** [comment]
dare risalto al titolo del sitting-item rispetto al titolo della seduta (in questa vista);

accorcia titoli degli atti a supporto (vedi link sulla destra)

**Comment by fspegni** [comment]
risolto
