### ISSUE TITLE
Assessori ripetuti nella pagina della Giunta

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#315]
Nella pagina della Giunta (http://senigallia.openmunicipio.it/institutions/city-government/) alcuni assessori appaiono più volte, con deleghe diverse.

**Comment by fspegni** [comment]
questo aspetto andrebbe discusso:
che facciamo quando un assessore compare piu' volte? lo enunciamo una volta solo, ed elenchiamo le sue deleghe? nella colonna "atti" facciamo la somma degli atti firmati con una delle due deleghe? il firmatario di un atto infatti e` un InstitutionCharge, e non una Person. 

personalmente credo si possa rispondere "si`" ad entrambe le domande, ma vorrei concordare questo aspetto prima di procedere

**Comment by guglielmo** [comment]
Nel modello non sono mappate le deleghe multiple per un singolo assessore, ma l'incarico di assessore.
Le deleghe sono nel campo di testo che descrive l'incarico di assessore.
