### ISSUE TITLE
Notifiche di monitoraggio con aggiornamenti vecchi

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#317]
Nella email di notifica dei monitoraggi compaiono aggiornamenti molto vecchi

![gmail - monitoraggio open municipio](https://f.cloud.github.com/assets/799159/560501/87f9024e-c476-11e2-8053-4183cfe7ea23.png)

**Comment by scaloni** [comment]
E' riaccaduto anche per senigallia.openmunicipio.it, con un atto del 2012 (http://senigallia.openmunicipio.it/acts/agendas/153/) segnalato il 14/03/2014

![2014-03-14_monitoring](https://f.cloud.github.com/assets/799159/2471011/67d6e768-b01d-11e3-84f3-d85b9fc0d0f8.png)

**Comment by scaloni** [comment]
Anche il 13/03/2014 sono stati notificati a http://senigallia.openmunicipio.it/users/profile/scaloni/ molte news di atti del 2012.
![2014-03-13_monitoring](https://f.cloud.github.com/assets/799159/2471044/112cfb22-b01e-11e3-92db-63464ef8feda.png)

**Comment by giovaandrea** [comment]
Se riguarda solo delibere di giunta forse è la conseguenza dei tag e titoli giornalistici che sto inserendo andando a ritroso. Anche oggi ne ho inseriti degli altri (sono arrivato a settembre 2012) per cui se il problema è quello dovrebbero arrivarne delle altre. Ma sempre e solo delibere di giunta

**Comment by scaloni** [comment]
ottimo @giovaandrea ; può essere quello il motivo @fspegni ?

**Comment by fspegni** [comment]
Diverse cose sono state risolte. Il problema dei tag e`"normale". Se c'e` anche qualche problema coi titoli giornalistici non so dirlo con esattezza, ma visto che questo altro ticket (https://github.com/openmunicipio/om-senigallia/issues/41) e` dedicato a quello, chiudo questo ticket
