### ISSUE TITLE
Stato della transizione di un emendamento non è una combobox

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#332]
Il campo Status delle transizioni di stato di un emendamento non permette di selezionare opzioni ma è rappresentato come un semplice campo di testo.

Si veda per esempio qui:
http://senigallia.openmunicipio.it/admin/acts/amendment/add/

**Comment by fspegni** [comment]
questo dipende dalla logica della funzione transition_form_factory(...) in acts/admin.py . essa dipendeva dall'_istanza_ di modello editato correntemente. l'ho corretto, e l'ho fatto dipendere dal _modello_ di atto editato correntemente. la differenza e`sostanziale, perche` in fase di inserimento (add), non esiste ancora nessuna istanza di modello definita, ma il modello e`gia` noto

```
def transition_form_factory(act_model):
...
    class RuntimeTransitionForm(forms.ModelForm):
        final_status = forms.ChoiceField(label='Status', choices=act_model.STATUS)

        class Meta:
            model = Transition
```

@guglielmo  e` d'accordo?
    return RuntimeTransitionForm
