### ISSUE TITLE
Interfaccia Admin: errore visualizzazione atti

### ISSUE THREAD

**Issue by davidfabri** [openpolis/open_municipio#334]
su interfaccia admin non funziona la visualizzazione degli atti (errore status)

**Comment by scaloni** [comment]
@davidfabri puoi specificare come riprodurre l'anomalia? Per esempio con quale modello si verifica?

**Comment by scaloni** [comment]
Aprire un atto generico (per esempio questo: http://senigallia.openmunicipio.it/admin/acts/act/373/), e non uno specifico (delibera, interpellanza, ecc): si genera l'errore seguente:

```
AttributeError at /admin/acts/act/373/ 
type object 'Act' has no attribute 'STATUS'
```
