### ISSUE TITLE
Variazioni Incarichi

### ISSUE THREAD

**Issue by davidfabri** [openpolis/open_municipio#336]
Il 4 luglio 2013 è stato variato un incarico: assessorato al turismo da Colocci a Mangialardi
Tale modifica non compare tra gli incarichi del sindaco (deleghe).

**Comment by fspegni** [comment]
Colocci (che aveva solo la delega al turoismo) si e` dimesso? Se no, che deleghe ha assunto Colocci?

**Comment by giovaandrea** [comment]
Ciao francesco, da una mail di campanelli:
Massimo Colocci, ex assessore alla promozione dei turismi  dimessosi lo scorso 17.11.2011. 
Le sue deleghe le ha prese il sindaco.

**Comment by scaloni** [comment]
Colocci si è dimesso, non sta più in Giunta ne in Consiglio

**Comment by fspegni** [comment]
Modifico il codice di Charge.denomination (in people/models.py) come segue:

```
    if self.institution.institution_type == Institution.MAYOR:
        denomination = _('Mayor').translate(settings.LANGUAGE_CODE)
        if self.description != "":
            denomination += ", %s" % self.description
        return denomination
```

In questo modo, il Sindaco puo` mostrare informazioni (deleghe) aggiuntive, riempiendo il campo "description". Guglielmo dovrebbe verificare @guglielmo
