### ISSUE TITLE
Emendamenti non importati

### ISSUE THREAD

**Issue by davidfabri** [openpolis/open_municipio#338]
Nell'incontro del 4/7/2013 abbiamo inserito alcuni emendamenti è necessario controllare la procedura di import/export

emendamenti inseriti:
DCC 20 del 2013 - emendamento n.1204 (fase 80)
DDC 10 del 2013 - emendamento n.1205
DDC 21 del 2013 - emendamento n.1206 (fase 74)

**Comment by scaloni** [comment]
Va verificato quale di questi emendamenti è attualmente esportato via OM-XML e se è correttamente importato in OM

**Comment by fspegni** [comment]
negli XML esportati da Infor (da febbraio ad oggi) non ce n'e` alcuno che contenga gli emendametni. ho eseguito questa ricerca in /home/omin/senigallia.openmunicipio.it/acts/

$ find . -iname '*.xml' -exec grep -i Emendation {} +

la quale prima seleziona tutti i file xml, e poi fa un grep della parola Emendation. credo sia da verificare con Infor

**Comment by fspegni** [comment]
era un problema di infor. è stata risolta, ora dobbiamo risolvere il problema della visualizzazione degli emendametni.

see #472
