### ISSUE TITLE
Dati non mostrati per le interpellanze

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#341]
Il frontend di una interpellanza non mostra molti dei campi presenti sul backend:
- proponenti (cioè firmatari) e destinatario
- stato di avvenuta risposta (c'è solo la data di "Presentazione" ma non di "Discussione")
- gli speech collegati (richiesta, risposta o altro).

Si veda per esempio qui:
http://senigallia.openmunicipio.it/acts/interpellations/464/

**Comment by scaloni** [comment]
La giustificazione del testo della richiesta e della risposta tronca le parole, come accade per tutti gli atti. Aprirò un ticket a parte

**Comment by scaloni** [comment]
Vedi https://github.com/openpolis/open_municipio/issues/354

**Comment by fspegni** [comment]
mostrare tutti gli speech relativi ad un'interpellanza (non solo domanda/risposta); eventuali parti scritte, mettere all'inizio. metti un "leggi tutto" dinamico.

**Comment by fspegni** [comment]
se un'interpellanza e` in stato "risposta", deve scattare la transizione relativa visibile dalla UI

**Comment by scaloni** [comment]
Su schermi widescreen, il testo della richiesta viene a sovrapporsi ai Destinatari.
Vedi qui:
http://senigallia.openmunicipio.it/acts/interpellations/463/

![issue-357](https://f.cloud.github.com/assets/799159/902138/6af65b2e-fb8f-11e2-8ef4-760f856c6838.jpg)

**Comment by scaloni** [comment]
Verifica anche la pagina delle interrogazioni, che deve essere sostanzialmente uguale a quella delle interpellanze

**Comment by scaloni** [comment]
Una interpellanza (per esempio http://senigallia.openmunicipio.it/acts/interpellations/658/) mostra soltanto la richiesta e la risposta, mentre dovrebbe mostrare tutti gli speech collegati (in genere sono tre, ma può accadere che siano anche più di tre, come in questo caso: http://senigallia.openmunicipio.it/acts/interpellations/655/).

Gli speech collegati vanno mostrati nel loro naturale ordine temporale; le etichette mostrate prima dello speech dipendono dal campo "Relation type":
- richiesta: "Richiesta orale"
- risposta: "Risposta orale"
- reference: "Replica"

Eventuali parti scritte vanno messe all'inizio, prima degli speech collegati.

Per ciascuna sezione di testo (scritto o orale) prevedere un "leggi tutto" dinamico.

**Comment by fspegni** [comment]
sto vedendo come implementare rapidamente il "Leggi tutto" (soprattutto per farlo via js) + lo stato di discussione.

**Comment by scaloni** [comment]
La replica è visualizzata prima della risposta!
http://senigallia.openmunicipio.it/acts/interpellations/690/

**Comment by scaloni** [comment]
In questo caso (http://senigallia.openmunicipio.it/acts/interpellations/729/), gli speech collegati sono quattro (ci sono due risposte) ma non ne viene mostrato il testo.

**Comment by scaloni** [comment]
Questa interpellanze ha addirittura 8 speech collegati
http://senigallia.openmunicipio.it/admin/acts/interpellation/751/

**Comment by scaloni** [comment]
vedi #430
