### ISSUE TITLE
Ordinamento tabella dei possibili firmatari di un atto

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#342]
Nella tabella mostrata per l'inserimento di un firmatario di un atto (http://senigallia.openmunicipio.it/admin/people/institutioncharge/?t=id), è più comodo avere le righe ordinate per cognome. Suggerisco di separare il cognome dal nome e dall'istituzione, prevedendo colonne separate o, in alternativa, separati da virgola.

**Comment by fspegni** [comment]
risolto in un commit di open-senigallia (essendo una personalizzazione delle viste di admin, credo sia preferibile definirle per la specifica istanza)

**Comment by scaloni** [comment]
@guglielmo ti occupi tu dell'eventuale merge da om-senigallia in open_municipio?

**Comment by scaloni** [comment]
Il fix è già online su http://senigallia.openmunicipio.it ? Il problema è ancora presente

**Comment by fspegni** [comment]
ma tu parli della tabella all'interno di un atto (es. la sezione "Act supports" in questo link http://senigallia.openmunicipio.it/admin/acts/deliberation/486/) oppure dell'ordinamento della form di ricerca dell'incarico istituzionale (che compare cliccando sulla lente di ingrandimento?)

**Comment by scaloni** [comment]
La seconda che dici, cioè l'ordinamento della form di ricerca dell'incarico istituzionale, che compare cliccando sulla lente di ingrandimento

**Comment by fspegni** [comment]
chiuso modificando i criteri di ordinamento di default per la vista di admin SenigalliaInsitutionCharge (v. repository open_senigallia)
