### ISSUE TITLE
Impossibile taggare un atto con un territorio

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#344]
Dal frontend di un atto (per esempio questo: http://senigallia.openmunicipio.it/acts/cgdeliberations/461/) è impossibile inserire un tag territoriale, sebbene questi compaiano nell'HTML della pagina (ma rimangono non visibili)

**Comment by fspegni** [comment]
campanelli mi ha detto che a senigallia non vogliono usare i tag territoriali. al momento, dunque, sono disabilitati da un flag presente nel file di configurazione (UI_LOCATIONS = False). semmai, quindi, il problema sarebbe togliere la visualizzazione dei tag territorio.

in alternativa (se campanelli & co ci hanno ripensato), riabilito l'uso dei tag territoriali.

**Comment by scaloni** [comment]
abilitiamo comunque il tagging dei territori, così li testiamo, poi la redazione stabilirà se utilizzarli a regime (come auspico) oppure no
