### ISSUE TITLE
Ordinamento sedute nell'aggiunta di un SittingItem

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#346]
Aggiungendo da backend un SittingItem, il campo Sitting presenta una lista di sedute (una select di tipo combo box) che però non sono ordinate in modo utile
Si veda a d esempio qui:
http://senigallia.openmunicipio.it/admin/people/sittingitem/add

Prevedere un ordinamento per data, partendo dalla più recente

**Comment by fspegni** [comment]
meglio usare un raw id field per le sedute (seguendo la filosofia di @guglielmo  per cui le select sono per le scimmie!!! :))
