### ISSUE TITLE
Categorie atto ipertestuali

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#351]
Per esempio qui (http://senigallia.openmunicipio.it/people/) rendere ipertestuali i nomi delle categorie di atto nella sezione "Atti presentati", in basso a destra.

**Comment by fspegni** [comment]
le interrogazioni non hanno una ricerca nella pagina degli atti (vedi http://senigallia.openmunicipio.it/acts/ ). per il momento quindi le interrogazioni non sono linkate

**Comment by scaloni** [comment]
Il link "Delibere" punta alle delibere di Giunta ma il numero mostrato accanto, nel cerchio azzurro, si riferisce invece alle delibere di Consiglio.

Vanno mostrati due link distinti: uno "Delibere di Consiglio" e uno "Delibere di Giunta"

**Comment by scaloni** [comment]
le interrogazioni ora hanno una ricerca nella pagina degli atti (vedi http://senigallia.openmunicipio.it/acts/), ma la voce "Interrogazioni" non è un ipertesto

**Comment by scaloni** [comment]
Lo stesso fix presente qui http://senigallia.openmunicipio.it/people/ andrebbe riportato anche qui:
http://senigallia.openmunicipio.it/institutions/council/

**Comment by scaloni** [comment]
Come non detto, essendo la pagina del Consiglio
