### ISSUE TITLE
Dimensioni incongrue per campo "Related act set" di un SittingItem

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#352]
Nell'aggiunta di un SittingItem, il campo "Related act set" è esageratamente largo e poco alto. Si veda ad esempio qui:
http://senigallia.openmunicipio.it/admin/people/sittingitem/add/

Ridurne la larghezza e ampliarne l'altezza (almeno 15 righe)

**Comment by fspegni** [comment]
usare raw_id
