### ISSUE TITLE
Font troppo piccolo in campi Text

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#353]
Occorrerebbe aumentare la dimensione del font del testo contenuto nei campi Text, ora è troppo piccolo.

**Comment by fspegni** [comment]
esempio di pagina admin e campo con font piccolo?

**Comment by scaloni** [comment]
![issue-353](https://f.cloud.github.com/assets/799159/900286/3d69ef54-fb5d-11e2-8ada-4894206a430e.jpg)

**Comment by fspegni** [comment]
issue chiusa dal commit https://github.com/openpolis/open_municipio/commit/feae352619e65755c9b65d43ef5724282889038e (per errore il commit riporta la chiusura di un'altra issue)
