### ISSUE TITLE
errore visualizzazione presenze

### ISSUE THREAD

**Issue by davidfabri** [openpolis/open_municipio#355]
Nella pagina delle votazioni quando si clicca in corrispondenza di Cicconi Massi e Mario Fiore si ha il seguente errore:

TypeError at /people/alessandro-cicconi-massi-1980-01-01/

can't compare datetime.date to NoneType

Request Method:     GET
Request URL:    http://senigallia.openmunicipio.it/people/alessandro-cicconi-massi-1980-01-01/
Django Version:     1.4.5
Exception Type:     TypeError
Exception Value:    

can't compare datetime.date to NoneType

Exception Location:     /home/open_municipio/senigallia.openmunicipio.it/private/venv/src/open-municipio/open_municipio/newscache/templatetags/newscache_tags.py in render, line 56
Python Executable:  /usr/bin/python
Python Version:     2.6.5
Python Path:    

['/home/open_municipio/senigallia.openmunicipio.it/private',
 '/usr/local/pythonenv/BASELINE/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg',
 '/usr/local/pythonenv/BASELINE/lib/python2.6/site-packages/pip-1.0.2-py2.6.egg',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/lib/python2.6/site-packages/pip-1.3.1-py2.6.egg',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/src/open-municipio',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/src/django-taggit',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/src/django-voting',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/src/django-model-utils',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/src/django-registration',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/src/django-profiles',
 '/usr/local/pythonenv/BASELINE/lib/python2.6',
 '/usr/local/pythonenv/BASELINE/lib/python2.6/plat-linux2',
 '/usr/local/pythonenv/BASELINE/lib/python2.6/lib-tk',
 '/usr/local/pythonenv/BASELINE/lib/python2.6/lib-old',
 '/usr/local/pythonenv/BASELINE/lib/python2.6/lib-dynload',
 '/usr/lib/python2.6',
 '/usr/lib/python2.6/plat-linux2',
 '/usr/lib/python2.6/lib-tk',
 '/usr/lib64/python2.6/lib-tk',
 '/usr/local/pythonenv/BASELINE/lib/python2.6/site-packages',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/lib/python2.6/site-packages',
 '/home/open_municipio/senigallia.openmunicipio.it/private/venv/lib/python2.6/site-packages/PIL']

Server time:    mer, 31 Lug 2013 21:35:44 +0200

**Comment by fspegni** [comment]
duplicato di https://github.com/openpolis/open_municipio/issues/349

chiuso, con riserva (vedi #349)
