### ISSUE TITLE
Import parziale di mozioni e ordini del giorno (agenda)

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#360]
Gli atti visibili (http://senigallia.openmunicipio.it/acts) per il 2013 presentano
- 4 ordini del giorno anziché 8
- 2 mozioni anziché 6; delle 2 presenti, solo una contiene il testo

Qui di seguito la lista completa di mozioni e ordini del giorno del 2013.

-- 6 mozioni --

17/01/2013 0000007 MOZIONE PRESENTATA DAL CONSIGLIERE GIACCHELLA AD OGGETTO: "ISTITUZIONE D UNO SPORTELLO ANTICRISI E PUNTO D'ASCOLTO SOCIO-ECONOMICO-ASSISTENZIALE" (http://senigallia.openmunicipio.it/acts/motions/15/)

14/03/2013 0000023 "MOZIONE PRESENTATA DAI CONSIGLIERI CAMERUCCIO, CICCONI MASSI, MAZZARINI, RIMINI AD OGGETTO: ""DISPOSIZIONI URGENTI PER LA TUTELA DELLA PULIZIA URBANA"

05/04/2013 0000026 "MOZIONE PRESENTATA DAI CONSIGLIERI BATTISTI, MANCINI E REBECCHINI PER IL RIPRISTINO DEL SERVIZIO MENSA NELLE SCUOLE MATERNE" (http://senigallia.openmunicipio.it/acts/motions/281/)

30/05/2013 0000042 "MOZIONE PRESENTATA DAI CONSIGLIERI CICCONI MASSI, RIMINI, MAZZARINI, CAMERUCCIO PER L'INTRODUZIONE DI AGEVOLAZIONI FISCALI APPLICABILI ALLE LOCAZIONI COMMERCIALI CON CANONI RIDOTTI"

18/06/2013 0000046 "MOZIONE PRESENTATA DAL CONSIGLIERE QUAGLIARINI AD OGGETTO: "PROGETTO DIALISI ESTIVA 2013"

18/06/2013 0000049 "MOZIONE PRESENTATA DAI CONSIGLIERI MONACHESI, CICCONI MASSI, CAMERUCCIO, BRUCCHINI, PERINI, GIROLAMETTI, RAMAZZOTTI SUL PATTO DI STABILITA'"

-- 8 ordini del giorno --

17/01/2013 0000003 "ORDINE DEL GIORNO PRESENTATO DAL CONSIGLIERE PARADISI AD OGGETTO: ""DIMISSIONI DEL SINDACO E DELLA GIUNTA" (http://senigallia.openmunicipio.it/acts/agendas/16/)

17/01/2013 0000008 "ORDINE DEL GIORNO PRESENTATO DAI CONSIGLIERI BATTISTI, MANCINI, REBECCHINI PER L'ADESIONE ALL'ASSOCIAZIONE FRA ENTI LOCALI AVVISO PUBBLICO" (http://senigallia.openmunicipio.it/acts/agendas/14/)

17/01/2013 0000009 "ORDINE DEL GIORNO PRESENTATO DAI CONSIGLIERI RAMAZZOTTI, GIROLAMETTI, BRUCCHINI, MONACHESI AD OGGETTO: ""CAMPAGNA REGIONALE AVVIATA PER LA REGOLAMENTAZIONE DEI SERVIZI SOCIO SANITARI E APPLICAZIONE DEI LIVELLI ESSENZIALI SOCIO SANITARI NELLE MARCHE" (http://senigallia.openmunicipio.it/acts/agendas/18/)

05/04/2013 0000029 "ORDINE DEL GIORNO PRESENTATO DAI CONSIGLIERI FIORE E GIACCHELLA AD OGGETTO: ""MODIFICA CRITERI DI DESIGNAZIONE SCRUTATORI DA ASSEGNARE AGLI UFFICI ELETTORALI DI SEZIONE" (http://senigallia.openmunicipio.it/acts/agendas/280/)

30/05/2013 0000043 "ORDINE DEL GIORNO PRESENTATO DAI CONSIGLIERI GIACCHELLA, PERGOLESI, GIROLAMETTI, MONACHESI AD OGGETTO: ""APPELLO PER IL RIFINANZIAMENTO DEGLI SGRAVI CONTRIBUTIVI PREVISTI DAL 1° COMMA DELL'ART. 4 DELLA LEGGE 236/93"

18/06/2013 0000048 "ORDINE DEL GIORNO PRESENTATO DAI CONSIGLIERI SARDELLA E FIORE PER L'ADESIONE AL ""MANIFESTO DEI SINDACI PER LA LEGALITA' CONTRO IL GIOCO D'AZZARDO"

19/07/2013 0000054 "ORDINE DEL GIORNO PRESENTATO DAI CONSIGLIERI RAMAZZOTTI, MONACHESI, BRUCCHINI, GIROLAMETTI SU RIORGANIZZAZIONE DEL SISTEMA SOCIO-SANITARIO MARCHE - RITIRO"

25/07/2013 0000068 "ORDINE DEL GIORNO PRESENTATO DAI CONSIGLIERI PERINI, MONACHESI, SARDELLA, BRUCCHINI, GIROLAMETTI AD OGGETTO: ""RIORGANIZZAZIONE DEL SISTEMA SOCIO SANITARIO MARCHE"

**Comment by fspegni** [comment]
ok. i dati sono presenti nei file xml. verifico perche` non vengono importati ...

**Comment by fspegni** [comment]
c'era un bug nell'importazione di Motion e Agenda. dovrebbe essere risolto

**Comment by scaloni** [comment]
@fspegni hai fatto push del fix? per il 2013 vedo correttamente 6 mozioni ma ancora soltanto 4 ordini del giorno (agenda)
http://senigallia.openmunicipio.it/acts/?q=&selected_facets=pub_date:[2013-01-01T00:00:00Z%20TO%202014-01-01T00:00:00Z]

**Comment by fspegni** [comment]
si`si`. avevo dimenticato di aggiornare l'indice del motore di ricerca. ora dovresti vedere tutto

**Comment by scaloni** [comment]
Per l'anno 2012 ci sono due ordini del giorno (così è indicato nel titolo) che sono stati caricati come mozioni:
- In merito a evasione ed elusione contributiva, al Comune risultano:
  - la mozione n. 67 del 19 luglio, che su OM è http://senigallia.openmunicipio.it/acts/motions/173/, è datata 18 luglio, e sia nel titolo che nell'oggetto è indicata come mozione;
  - l'ordine del giorno n. 78 del 10 ottobre, che su OM è una mozione, http://senigallia.openmunicipio.it/acts/motions/104/, ed è datata 20 settembre, ed è indicata come mozione nel titolo, e come ordine del giorno nell'oggetto
- In merito al mantenimento del giudice di pace, al Comune risulta l'ordine del giorno n. 8 del 26 gennaio che su OM è la mozione http://senigallia.openmunicipio.it/acts/motions/187/ ma è del 25 gennaio, e sia nel titolo che nell'oggetto è indicata come ordine del giorno.

Le date in OM coincidono con quelle nel testo.

**Comment by scaloni** [comment]
Tra le 41 mozioni del 2011 presenti in OM, 19 sono vere mozioni, mentre i restanti 22 atti non sono mozioni: 9 sono delibere di Consiglio e 13 sono Ordini del Giorno.
Tra di essi ci sono tutti gli Ordini del Giorno indicati dal Comune per il 2011 (sono in tutto 13).

Ecco il dettaglio:
- http://senigallia.openmunicipio.it/acts/motions/179/ ORDINE DEL GIORNO 26/10/2011 n. 98
- http://senigallia.openmunicipio.it/acts/motions/182/ ORDINE DEL GIORNO 26/10/2011 n. 97
- http://senigallia.openmunicipio.it/acts/motions/169/ MINUTO DI SILENZIO 28/07/2011 N° 77 
- http://senigallia.openmunicipio.it/acts/motions/209/ MINUTO DI SILENZIO 27/07/2011 N° 69 
- http://senigallia.openmunicipio.it/acts/motions/61/  ORDINE DEL GIORNO 06/07/2011 N° 59 
- http://senigallia.openmunicipio.it/acts/motions/62/  APPROVAZIONE VERBALI 06/07/2011 N° 58 
- http://senigallia.openmunicipio.it/acts/motions/110/ ORDINE DEL GIORNO 06/06/2011 N° 55 
- http://senigallia.openmunicipio.it/acts/motions/111/ APPROVAZIONE VERBALI 06/06/2011 N° 54 
- http://senigallia.openmunicipio.it/acts/motions/166/ CONSIGLIO GRANDE 28/05/2011 N° 52 
- http://senigallia.openmunicipio.it/acts/motions/102/ VERIFICA STATO DI ATTUAZIONE 28/04/2011 N° 49 
- http://senigallia.openmunicipio.it/acts/motions/71/  APPROVAZIONE VERBALI 13/04/2011 N° 38 
- http://senigallia.openmunicipio.it/acts/motions/78/  VERBALE 13/04/2011 N° 36 
- http://senigallia.openmunicipio.it/acts/motions/93/  COMUNICAZIONI DEL SINDACO 13/04/2011 N° 37 
- http://senigallia.openmunicipio.it/acts/motions/99/  ORDINE DEL GIORNO 13/04/2011 N° 41 
- http://senigallia.openmunicipio.it/acts/motions/157/ ORDINE DEL GIORNO 30/03/2011 N° 27 
- http://senigallia.openmunicipio.it/acts/motions/46/  ORDINE DEL GIORNO 30/03/2011 N° 34 
- http://senigallia.openmunicipio.it/acts/motions/134/ ORDINE DEL GIORNO 09/03/2011 N° 18 
- http://senigallia.openmunicipio.it/acts/motions/146/ ORDINE DEL GIORNO 09/03/2011 N° 22 
- http://senigallia.openmunicipio.it/acts/motions/70/  ORDINE DEL GIORNO 09/03/2011 N° 16 
- http://senigallia.openmunicipio.it/acts/motions/75/  ORDINE DEL GIORNO 26/01/2011 N° 5 
- http://senigallia.openmunicipio.it/acts/motions/91/  ORDINE DEL GIORNO 26/01/2011 N° 6 
- http://senigallia.openmunicipio.it/acts/motions/97/  ORDINE DEL GIORNO 26/01/2011 N° 4

**Comment by scaloni** [comment]
Per quanto riguarda il 2010, in OM non esiste nessuna agenda mentre ci sono soltanto 2 mozioni:
- http://senigallia.openmunicipio.it/acts/motions/172/ è una delibera di Consiglio (contiene una discussione, senza un vero atto deliberato);
- http://senigallia.openmunicipio.it/acts/motions/118/ è l'ordine del giorno n. 135 datato 21/12/2010 e intitolato 'ORDINE DEL GIORNO PRESENTATO DAL SINDACO AD OGGETTO "MORATORIA SULLE SCADENZE DEL DECRETO RONCHI" ' che è l'unico, nella lista di mozioni e ordini del giorno fornitaci dal Comune per il 2010, ad avere il campo "TIPO ATTO" diverso da "OLD".
