### ISSUE TITLE
Valore mancante nel campo "Iniziativa"

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#366]
Alcune delibere di Giunta presentano un valore mancante nel campo "Iniziativa" (nella sezione "Presentazione")

Per esempio si veda qui:
http://senigallia.openmunicipio.it/admin/acts/cgdeliberation/461/

**Comment by scaloni** [comment]
@fspegni che ne pensi? il data_import non recupera quel dato? Essendo un campo obbligatorio, per modificare l'atto siamo obbligati a popolarlo (per ora inseriamo Giunta)

**Comment by fspegni** [comment]
questo ora non capita, quindi il problema e` stato risolto
