### ISSUE TITLE
Titolo aggiuntivo non mostrato

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#367]
Il contenuto del titolo aggiunto non viene mostrato nel frontend in sostituzione del titolo originario

Si veda ad esempio questo atto:
frontend: http://senigallia.openmunicipio.it/acts/cgdeliberations/386/
backend: http://senigallia.openmunicipio.it/admin/acts/cgdeliberation/386/

**Comment by scaloni** [comment]
Viene mostrato il titolo e non il titolo aggiunto nei seguenti casi:
- in home page (http://senigallia.openmunicipio.it/), nella sezione "Ultimi atti presentati dai politici";
- nella pagina di un politico (es. http://senigallia.openmunicipio.it/people/simone-ceresoni-2012-10-19/) nelle sezioni "Atti su cui lavora" e "Ultime su Nome Cognome";
- nella pagina del Consiglio (http://senigallia.openmunicipio.it/institutions/council/), nella sezione "Ultimi 3 atti del Consiglio", in basso a destra;
- nel pop-up di un Event, nella sezione "Atti in discussione"
- nel titolo della pagina, come indicato dal browser ("Open municipio - Dettaglio atto ...")
  ![issue-367](https://f.cloud.github.com/assets/799159/1012643/da23e45a-0b73-11e3-92e8-207840eb61f1.png)

**Comment by fspegni** [comment]
per la sezione "Ultime notizie su <nome> <cognome>", occorre rigenerare le notizie. Il titolo dell'atto, infatti, viene incluso nel testo della notizia quando quest'ultima viene generata.

**Comment by scaloni** [comment]
Viene mostrato il titolo dell'atto e non quello giornalistico nella sezione "Atti a supporto della discussione", per esempio qui:

http://senigallia.openmunicipio.it/sittings/item/11/
http://senigallia.openmunicipio.it/sittings/item/9/

**Comment by scaloni** [comment]
@fspegni la generazione delle nuove notizie userà il titolo giornalistico?

**Comment by fspegni** [comment]
Allora,

quando mi hai scritto la risposta era "no". Adesso ho modificato i
template che generano la news alla modifica dell'atto per mostrare il
titolo giornalistico (se presente), altrimenti il titolo.

L'ostacolo che vedo io e`che in fase di importazione l'atto non ha
ancora un titolo giornalistico, quindi la news generata in fase di
presentazione sara` sempre basata sul titolo dell'atto.

Eventuali news successive (es. se l'atto viene firmato a seguito della
presentazione, da un politico), possono invece mostrare il titolo
giornalistico, se nel frattempo e` stato specificato.

Tuttavia quest'ultimo caso mi pare che non si verifichi praticamente mai
nel ns caso (da noi la firma dell'atto e` quella al momento della
presentazione e basta).

Ad ogni modo, non vedo come poter generare le news relative alla
presentazione di un atto con il titolo giornalistico, dal momento che
questo viene specificato in un tempo successivo.

Che ne pensate?

FS

Il giorno mar, 18/02/2014 alle 23.33 -0800, Marco Scaloni ha scritto:

**Comment by scaloni** [comment]
Capisco il problema.
Non so se può essere superato con la rigenerazione delle news, magari solo quelle delle ultime 24 ore, da effettuarsi prima dell'invio della newsletter. E' fattibile?
