### ISSUE TITLE
Presidente e vice presidente di commissione non mostrato

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#371]
Si veda ad esempio qui:
http://senigallia.openmunicipio.it/institutions/committees/commissione-1/

Attualmente l'informazione è stata inserita tra le opzioni avanzate dell'incarico istituzionale collegato alla commissione (campo Descrizione).
Indicare se esiste un'alternativa.

**Comment by scaloni** [comment]
Se nella pagina di un incarico istituzionale di Commissione (per esempio qui: http://senigallia.openmunicipio.it/admin/people/institutioncharge/141/) si aggiunge un elemento inline "Responsabilità istituzionali", con valore di "President", si ottiene un errore da frontend (nell'esempio: http://senigallia.openmunicipio.it/institutions/committees/commissione-1/).

**Comment by fspegni** [comment]
Ok, l'approccio giusto è quello di specificare la responsabilità istituzionale. Occorre tuttavia popolare il campo "incarico istituzionale originale" per collegare questa carica a quella "originale", ovvero quella di consigliere.
