### ISSUE TITLE
Interpellanze e interrogazioni non selezionabili come EventAct

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#372]
Nella pagina di un evento (per esempio: http://senigallia.openmunicipio.it/admin/events/event/1/), volendo selezionare un atto attraverso il campo raw id "Act", cliccando sulla lente di ingrandimento (link a http://senigallia.openmunicipio.it/admin/acts/act/?t=id), dalla lista degli atti non è possibile selezionare quelli che non hanno un campo Idnum (cioè interpellanze e interrogazioni)

Prevedere anche l'aggiunta di un campo che indichi il tipo di atto.

**Comment by fspegni** [comment]
una soluzione e`rendere cliccabile il titolo (anziche` l'idnum). l'ho implementata nel repository om-senigallia, perche' non so se @guglielmo e` d'accordo (commenti da @guglielmo  ?). 

il campo aggiuntivo per mostrare il tipo di atto per il momento lo lascio in sospeso (una soluzione sarebbe: aggiungere una property al modello act, che stampi la classe speifica dell'istanza di atto)
