### ISSUE TITLE
Login con Facebook/Google/Twitter fallisce

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#375]
http://senigallia.openmunicipio.it/login/facebook/ restituisce l'errore:

```
WrongBackend at /login/facebook/
Incorrect authentication service "facebook"
```

http://senigallia.openmunicipio.it/login/google-oauth2/ restituisce l'errore:

```
WrongBackend at /login/google-oauth2/
Incorrect authentication service "google-oauth2"
```

http://senigallia.openmunicipio.it/login/twitter/ restituisce l'errore:

```
WrongBackend at /login/twitter/
Incorrect authentication service "twitter"
```

**Comment by scaloni** [comment]
l'autenticazione deve essere comune e condivisa da tutte le istanze della piattaforma openmunicipio.it, per cui gli utenti, una volta ottenuto l'accesso, possono utilizzarlo su ogni istanza (eventualmente con permessi diversi)

**Comment by guglielmo** [comment]
Non abbiamo progettato, né implementato il single sign-on, vanno generate le chiavi per ogni istanza.

**Comment by fspegni** [comment]
l'autenticazione fb e g+ ora funziona (con le istruzioni di @guglielmo ). appena riesco, applico anche le modifiche per twitter
