### ISSUE TITLE
Errato conteggio degli atti collegati ad un argomento

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#376]
Nella pagina di un certo argomento (per esempio http://senigallia.openmunicipio.it/categories/bilancio/)
- il conteggio degli atti della categoria "Proposte di delibera" non coincide con il numero di documenti trovati cliccando sul numero (nell'esempio, il numero "12" rimanda ad un solo documento)
- è assente il numero relativo agli "Ordini del giorno", anche se esistono atti di tipo "Agenda" taggati con quell'argomento (per esempio si veda http://senigallia.openmunicipio.it/acts/agendas/470/ taggato con http://senigallia.openmunicipio.it/tags/ospedali-e-cliniche/)
- è assente la riga dedicata alle delibere di Giunta
- "Delibere" dovrà diventare "Delibere di Consiglio"

**Comment by fspegni** [comment]
ora solo il numero delle proposte di consiglio sembra errato. genera una url con "is_proposal=sì". eliminando quella parte, si vedono tutte le delibere ed il numero coincide. rivedere la logica con cui viene generata la tabella

**Comment by fspegni** [comment]
la causa del problema e` che la pagina web controlla quegli atti che hanno l'attributo approval_date nullo, mentre l'attributo di ricerca "is_proposal" ritorna quegli atti che anno final_idnum=''. per coerenza, anche il template dovrebbe calcolare sulla base dell'attributo final_idnum

**Comment by fspegni** [comment]
mi pare che il problema dei conteggi sia risolto. se rimane qualcosa per ristrutturare l'interfaccia di questa sezione, conviene chiudere questo ed aprire dei ticket a parte. che ne pensi? @scaloni

**Comment by scaloni** [comment]
ok @fspegni
