### ISSUE TITLE
Sedute doppie nella stessa data

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#377]
Verificare perché sono state prodotte e come bonificarle. Ecco quelle presenti:
- 21 aprile 2010
- 9 giugno 2010
- 25 gennaio 2012

**Comment by fspegni** [comment]
- questa del 21 aprile e` vuota (non c'e''nessuna votazione nel file .mdb, tutti i politici sono assenti) http://senigallia.openmunicipio.it/sittings/consiglio-comunale-00-2010-04-21-69/
- questa del 25 gennaio 2012 (seduta con id 3, http://senigallia.openmunicipio.it/sittings/consiglio-comunale-03-2012-01-25-88/ ) in realta' si e' tenuta il 12 maggio 2010. la natura dell'errore non e' identificata. la data della seduta e` la seguente: ("05/12/10")
- esistono due gruppi di file MDB con data della seduta uguale a 9 giugno 2010: quelli con ID seduta 05, e quelli con ID seduta 41. ad occhio, la seduta 05 dovrebbe essere avvenuta in quella data, mentre la 41 dovrebbe essere avvenuta nel 2012 (in realta' la 39 risulta nel 2012, la 40 nel 2010, e la 41 nel 2010. forse qualcuno ha erroneamente manipolato la data sul pc che genera i file?)

posso risolvere manualmente questa configurazione, ma si potrebbe avere dal comune una lista ufficiale con tutte le sedute di consiglio della legislatura?

**Comment by scaloni** [comment]
Queste sono le convocazioni del Consiglio:

2010 (15 convocazioni):
2010-04-14, 2010-04-21, 2010-05-12, 2010-05-25, 2010-06-09, 2010-07-07, 2010-07-28, 2010-09-22, 2010-10-09, 2010-10-13, 2010-10-27, 2010-11-10, 2010-11-24, 2010-12-01, 2010-12-21

2011 (17 convocazioni):
2011-01-26, 2011-02-09, 2011-03-09, 2011-03-30, 2011-04-13, 2011-04-18, 2011-04-28, 2011-05-28, 2011-06-06, 2011-07-06, 2011-07-27, 2011-09-14, 2011-09-28, 2011-10-26, 2011-11-16, 2011-11-29, 2011-12-19

2012 (11 convocazioni):
2012-01-25, 2012-02-27, 2012-03-21, 2012-03-28, 2012-04-18, 2012-05-17, 2012-06-20, 2012-07-18, 2012-09-19, 2012-10-30, 2012-11-28

2013 (ad oggi ci sono state 11 convocazioni)
2013-01-16, 2013-02-13, 2013-03-13, 2013-04-04, 2013-04-22, 2013-05-22, 2013-05-29, 2013-06-12, 2013-06-18, 2013-07-17, 2013-07-24

**Comment by fspegni** [comment]
sto modificando a mano le sedute:
**\* 2010 ***
- ho aggiornato la data della sedute idnum=3 (controllare se le votazioni associate sono quelle giuste)
- nascosta la seduta con data 20 maggio 2010. (SeniS9901.Mdb) era un seduta di prova
- nascosta la seduta con data errata 26 maggio 2010. (SeniS4001.Mdb) non si capisce perche`
- nascosta la seduta con data 9 giugno 2010. (SeniS4101.Mdb) idem con patate
- nascosta la seduta con data 8 luglio 2010 (SeniS0705.Mdb e successivi). vedere votazioni collegate
- nascosta la seduta con data 29 luglio 2010 (SeniS0907.Mdb e successivi). vedere votazioni collegate
- nascosta la seduta con data 22 dicembre 2010 (SeniS1801.Mdb e successivi). vedere votazioni collegate

**\* 2011 ***
- nascosta seduta con data 7 luglio 2011 (SeniS2908.Mdb e successivi). vedere votazioni
- nascosta seduta con data 28 luglio 2011 (SeniS3107.Mdb e successivi). vedere votazioni
- nascosta seduta con data 20 dicembre 2011 (SeniS3902.Mdb e successivi). vedere votazioni

**\* 2012 ***
- nascosta seduta con data 28 febbraio 2012 (SeniS4308.Mdb e successivi). vedere votazioni
- nascosta seduta con data 29 marzo 2012 (SeniS4603.Mdb e successivi). vedere votazioni
- nascosta seduta con data 19 aprile 2012 (SeniS4808.Mdb e successivi). vedere votazioni
- nascosta seduta con data 20 settembre 2012 (SeniS5304.Mdb e successivi). vedere votazioni
- nascosta seduta con data 31 ottobre 2012 (SeniS5509.Mdb e successivi). vedere votazioni
- nascosta seduta con data 29 novembre 2012 (SeniS5703.Mdb e successivi). vedere votazioni

**\* 2013 ***
- nascosta seduta con data 18 luglio 2013 (SeniS6803.Mdb e successivi). vedere votazioni

**Comment by fspegni** [comment]
il file ODG100728.txt (https://www.dropbox.com/sh/t891n1eew4rms0w/ahTR1NpzJV/2010/ODG100728.txt) contiene l'odg di una seduta di settembre

**Comment by scaloni** [comment]
Ora il file è corretto: https://www.dropbox.com/sh/t891n1eew4rms0w/ahTR1NpzJV/2010/ODG100728.txt
