### ISSUE TITLE
IntegrityError su modifica dell'atto

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#382]
Modificando da backend il titolo aggiunto di una delibera di consiglio (http://senigallia.openmunicipio.it/admin/acts/deliberation/474/) si ottione un IntegrityError ("null value in column "category_id" violates not-null constraint")

**Comment by fspegni** [comment]
see #401

**Comment by scaloni** [comment]
L'errore si ottiene spesso ma non sistematicamente.
L'atto http://senigallia.openmunicipio.it/admin/acts/deliberation/22/ ha prodotto errore in presenza del tag "consiglio comunale" mentre non ha prodotto errore con il campo tag lasciato vuoto

**Comment by scaloni** [comment]
Una lista di atti che presentano l'errore (da verificare) è la seguente:
http://senigallia.openmunicipio.it/admin/acts/deliberation/101/
http://senigallia.openmunicipio.it/admin/acts/deliberation/215/
http://senigallia.openmunicipio.it/admin/acts/deliberation/31/
http://senigallia.openmunicipio.it/admin/acts/deliberation/67/
http://senigallia.openmunicipio.it/admin/acts/deliberation/115/
http://senigallia.openmunicipio.it/admin/acts/deliberation/35/
http://senigallia.openmunicipio.it/admin/acts/deliberation/55/
http://senigallia.openmunicipio.it/admin/acts/deliberation/178/
http://senigallia.openmunicipio.it/admin/acts/deliberation/108/
http://senigallia.openmunicipio.it/admin/acts/deliberation/85/
http://senigallia.openmunicipio.it/admin/acts/deliberation/136/
http://senigallia.openmunicipio.it/admin/acts/deliberation/141/
http://senigallia.openmunicipio.it/admin/acts/deliberation/236/
http://senigallia.openmunicipio.it/admin/acts/deliberation/162/

**Comment by scaloni** [comment]
l'atto http://senigallia.openmunicipio.it/admin/acts/deliberation/22/ presenta il campo "Categorie" con nessun valore selezionato, mentre da frontend è presente correttamente la categoria "Pubblica Amministrazione" (http://senigallia.openmunicipio.it/acts/deliberations/22/)

**Comment by fspegni** [comment]
ho inserito nella schermata di admin degli atti un inline apposito per tag/categorie. l'inserimento dei tag/categorie tramite inline risulta un po' macchinoso, ma almeno e` corretta e non genera errore.
