### ISSUE TITLE
Informazioni assenti per i consiglieri non più in carica

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#383]
Per i consiglieri non più in carica (per esempio http://senigallia.openmunicipio.it/people/tiziano-pazzani-1980-01-01/) non sono mostrate molte delle informazioni presenti invece per i consiglieri in carica (per esempio http://senigallia.openmunicipio.it/people/roberto-mancini-1980-01-01/):
- nella pagina del politico
  - le cariche, sotto la fotografia, con l'indicazione dei periodi relativi ad una determinata carica
  - le presenze
  - voti chiave
  - atti su cui lavora (cioè ha lavorato)
  - argomenti di cui si occupa (o di cui si è occupato)

**Comment by fspegni** [comment]
Mostrare le informazioni dell'incarico istituzionale piu' recente in ordine di tempo

duplicate #392

**Comment by fspegni** [comment]
duplicato di #579
