### ISSUE TITLE
Assente il gruppo di appartenenza per ex consiglieri o subentrati

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#386]
Nelle statistiche mostrate nella pagine del Consiglio (http://senigallia.openmunicipio.it/people/), come "I più presenti al voto" oppure "I consiglieri con più atti", i consiglieri non più in carica (come Pazzani) e quelli subentrati (come Perini) non mostrano il partito di appartenenza.

**Comment by giovaandrea** [comment]
Idem nella parte votazioni
http://senigallia.openmunicipio.it/votations/688/

**Comment by scaloni** [comment]
per le votazioni il gruppo dovrà essere quello valido alla data di votazione

**Comment by fspegni** [comment]
per le statistiche della consigliatura, mostrare solo consiglieri in carica (nascondi dimissionari)

**Comment by fspegni** [comment]
mostrare gruppo di appartenenza di un consigliere al momento della firma di un atto (particolarmente interessante per consiglieri che hanno dato le proprie dimissioni):

http://senigallia.openmunicipio.it/acts/interrogations/604/
