### ISSUE TITLE
Importazione incompleta delle delibere di Giunta

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#389]
Ad esempio per il 2012 le delibere di Giunta in OM sono soltanto 4 anziché 243.

Si veda il dettaglio in questo documento:
https://www.dropbox.com/sh/2j9lweti6hl1zkz/9-1S36B5bD/Elenco-atti-Consiglio%2BGiunta.ods

**Comment by scaloni** [comment]
Per esempio la delibera di Giunta del 04/12/2012 dal titolo che inizia per "BANDO DI CONCORSO “L’HO FATTO IO” RIVOLTO ALLE SCUOLE PRIMARIE E SECONDARIE DI 1° GRADO" è contenuta nei file OM-XML seguenti:
- 2013/04/30/02/20.xml
- 2013/04/30/02/20.xml
- 2013/04/30/02/20.xml
- 2013/05/22/01/20.xml
- 2013/05/22/01/20.xml
- 2013/05/22/01/20.xml

**Comment by fspegni** [comment]
Caricato su dropbox la lista completa delle delibere di giunta esportate da Infor. Il file e` scaricabile a questo link:

https://www.dropbox.com/s/y0ltrykf53cn9sm/cg_deliberation.txt

Per ogni delibera di giunta è riportata la sola riga di intestazione (contenente il codice utilizzato dal comune per identificare una delibera. Poiché Infor duplica le informazioni esportate, consiglio di eseguire questo comando per separare le delibere di un singolo anno:

grep <anno> cg_deliberation.txt | cut -d " " -f 4 | sort | uniq

ecco quante delibere di giunta ci sono per ciascun anno:
2010 -> 52
2011 -> 17
2012 -> 7
2013 -> 111

Mi pare di capire che c'e` qualche bug nella procedura di esportazione di Infor

**Comment by fspegni** [comment]
ok, era un problema di infor. risolta l'esportazione delle delibere di giunta, occorre verificare che abbiano specificato correttamente:
- tutti i consiglieri firmatari (allo stesso livello) di ciascun atto
- che anche le delibere di giunta esportino i propri allegati
