### ISSUE TITLE
Scheduling module

### ISSUE THREAD

**Issue by guglielmo** [openpolis/open_municipio#39]
It's a module for the visualization of the future events in the Comune.

It will help citizens track important events (discussions or votings) that will happen in the future.

An event is composed by:
-  a date (no time)
- a reference (foreign key) to an act
- the site where it will happen (council, citygov, commission), a link to an Institution in our case

Information may be inserted and managed by editors, from a backend interface,
or automatically integrated into the system by an integration script (henever that's possible).

**Comment by seldon** [comment]
May an event  refer to a votation ? In that case, how this piece of info would be included inside the `Event` object ? As a foreign key to `Votation` ?

**Comment by guglielmo** [comment]
No, an event maps something that will happen in the future related to acts, only. 

As a matter of fact, usually this _something_ is a final votation, but it will only happen in the future, it's not yet in our system and it can not be linked.

**Comment by ghost** [comment]
Do we need some extra field to insert a description? I am thinking of a "Notes" or "Description" text field.

**Comment by guglielmo** [comment]
I tubini that a description field could be useful.

**Comment by guglielmo** [comment]
I think (tubini was the phone autocompleter)

**Comment by ghost** [comment]
Do we need those events to be reachable with a standard url hierarchy?

Eg:
events/ -> event_list.html
events/12/ -> event_detail.html

As an alternative, I guess an inclusion tag could fit as well. This would provide us with handy html chunks to show event lists wherever needed in our templates.

**Comment by guglielmo** [comment]
There's no need of an event_detail view or template.
Events relate to an act and the link brings directly to the act.

The extractions that we will need (at least the ones I can see now):
- a global list of events in the future
- all future events related to an act (for the act_detail view)
- all future events related to acts tagged with a tag or a category
- future events related to the acts that a single politician has signed

As events we're interested in are only future events, it may be useful to define a custom default manager,
that filters events, removing those in the past, with relation to the current date.
