### ISSUE TITLE
Registrazione di un utente produce errore DoesNotExist

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#393]
La registrazione di un nuovo utente (registrazione interna ad OM, senza uso di autenticazioni esterne, per esempio Facebook) fallisce; si ottiene il seguente

```
DoesNotExist at /accounts/register/
Group matching query does not exist.
```

**Comment by fspegni** [comment]
l'installazione di OM deve prevedere un gruppo chiamato "politicians". verificare se e` documentato da qualche parte

**Comment by scaloni** [comment]
Gruppo in che senso?

**Comment by scaloni** [comment]
La mail di conferma registrazione è arrivata correttamente, però se si clicca sul link di conferma (http://senigallia.openmunicipio.it/accounts/activate/af716382f780d3cae2f38c9d87e74f5002adcb29/) si ottiene un errore (non tradotto in italiano)

```
There was an error creating this account. Perhaps your registration key expired, in which case please re-register.
```

**Comment by fspegni** [comment]
per gruppo intendo un gruppo all'interno di Open Senigallia (vedi pannello di admin / groups). per l'errore, indago.

**Comment by scaloni** [comment]
Ma se si aggiunge un gruppo, questo è visibile da UI al pari dei veri gruppi consiliari?

**Comment by fspegni** [comment]
no. i gruppi consiliari si trovano in people / groups (nonostante l'omonimia, i due gruppi sono in realta` classi di modello diverse)

**Comment by fspegni** [comment]
a me il link di attivazione dell'utente inviato via mail funziona. tu hai riprovato? se ti funziona chiuderei il ticket

**Comment by scaloni** [comment]
Ora funziona, ho registrato un mio account. Hai scoperto per quale motivo tre giorni fa non funzionava?

**Comment by scaloni** [comment]
@fspegni puoi creare un ticket (milestone Future) per prevedere la creazione automatica del gruppo "politicians" al momento del deployment? (se è sufficiente questo)
