### ISSUE TITLE
Lista delle località non ordinata

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#394]
Nella pagina di registrazione di un nuovo utente (http://senigallia.openmunicipio.it/accounts/register/), la lista delle località non è ordinata alfabeticamente.

**Comment by scaloni** [comment]
La lista appare non ordinata nella pagina di registrazione con autenticazione esterna (Google, Twitter, Facebook)
http://senigallia.openmunicipio.it/login-form/

**Comment by giovaandrea** [comment]
... visto che ci siamo, manca la località Bettolelle, vogliamo accorparla a Filetto senza crearne una nuova?

**Comment by fspegni** [comment]
se si accede all'url segnalata da marco "direttamente" (senza aver cioe`essere passati dalla form di registrazione e cliccato su un bottone social) si ottiene un'eccezione con scritto "Partial Pipeline". vedere se si puo` mostrare una scherata piu` amichevole (o rimandare alla pagina di registrazione)

**Comment by scaloni** [comment]
@giovaandrea località "Filetto" rinominata "Bettolelle - Filetto" http://senigallia.openmunicipio.it/locations/bettolelle-filetto/
