### ISSUE TITLE
Le descrizioni dei termini sono assenti

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#399]
Sono assenti le descrizioni dei termini, visualizzabili cliccando sul cerchietto grigio con un punto interrogativo affiancato al termine descritto.

Il termine è visualizzato in forma sintetica, con le parole separate da trattini (es. "argomenti-piu-discussi"), mentre al posto della descrizione compare la frase inglese "Term not yet defined.".

Il problema è presente:
- 4 volte in home page ("Cosa succede in comune", "Atti in evidenza", "Ultimi voti chiave", "Argomenti più discussi")
- nella pagina della Giunta (http://senigallia.openmunicipio.it/institutions/city-government/), accanto al titolo "Giunta"
- nella pagina del Consiglio (http://senigallia.openmunicipio.it/institutions/council/), accanto al titolo "Consiglio"
- nella pagina delle Commissioni (http://senigallia.openmunicipio.it/institutions/committees/), accanto al titolo "Commissioni"
- nella pagina dei Gruppi (http://senigallia.openmunicipio.it/institutions/groups/), accanto al titolo "Gruppi"
- 2 volte nella pagina di un atto (per es. http://senigallia.openmunicipio.it/acts/deliberations/483/), nei titoli "Argomenti dell'atto" e "Monitora"
- 2 volte nella pagina degli argomenti (http://senigallia.openmunicipio.it/topics/), nei titoli "Peso degli argomenti negli atti" e "Argomenti più monitorati"
- 2 volte nella pagina di un argomento (ad esempio http://senigallia.openmunicipio.it/categories/societa/), nei titoli "Monitora" e "Altri argomenti in ..."
- 4 volte nella pagina "Cittadini" (http://senigallia.openmunicipio.it/users/), nei titoli "Politici più monitorati", "Argomenti più monitorati", "Atti più monitorati" e "Ultimi iscritti".

Non si escluse sia presente anche altrove.

**Comment by scaloni** [comment]
![ticket-399](https://f.cloud.github.com/assets/799159/1072122/751fdb72-1488-11e3-8327-a7f1a27163b4.png)

**Comment by fspegni** [comment]
occorre riempire le righe in questo modello:

http://senigallia.openmunicipio.it/admin/idioticon/term/

(vedi esempio con il termine giunta-comunale). il termine da tradurre e` quello che appare ora cliccando sul "?". per vedere il testo da inserire, copierei le descrizione date da open-udine.

essendo una cosa da inserire da interfaccia, potete prenderlo in carico tu, marco, o @giovaandrea?

**Comment by scaloni** [comment]
Si, ce ne occupiamo io e @giovaandrea
