### ISSUE TITLE
Impossibile definire un "atto-chiave" da backend

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#401]
Per impostare un atto come "atto-chiave"
- nella scheda dell'atto specifico (per esempio http://senigallia.openmunicipio.it/admin/acts/cgdeliberation/451/) non è possibile, mancando il campo "is_key"
- nella scheda dell'atto generico (http://senigallia.openmunicipio.it/admin/acts/act/451/) c'è il campo "is_key" ma salvando si ottiene un IntegrityError:
  
  IntegrityError at /admin/acts/act/451/
  null value in column "category_id" violates not-null constraint

**Comment by scaloni** [comment]
Aggiungere is_key al backend dell'atto specifico.

**Comment by scaloni** [comment]
Utilizzando l'interfaccia di frontend sono stati già definiti alcuni atti chiave (http://senigallia.openmunicipio.it/acts/?q=&selected_facets=is_key:s%C3%AC)

**Comment by scaloni** [comment]
Da admin il campo is_key non è disponibile per le delibere di Giunta e le mozioni

**Comment by fspegni** [comment]
il problema e` stato risolto
