### ISSUE TITLE
Aggiornare le informazioni sui gruppi consiliari

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#403]
Le informazioni al momento caricate non sono aggiornate. Ci sono consiglieri che sono passati al misto (Rebecchini) e c'è un gruppo di nuova istituzione (udc - scelta civica per senigallia).

Sul sito del Comune risulta questo
http://www.comune.senigallia.an.it/site/senigallia/live/taxonomy/senigallia/vado_in_comune/organi/il-consiglio-comunale/componenti.html

**Comment by scaloni** [comment]
Il gruppo "Futuro e Libertà" compare due volte nell'admin (http://senigallia.openmunicipio.it/admin/people/group/13/ e http://senigallia.openmunicipio.it/admin/people/group/14/) e in entrambi i casi è collegato a delle votazioni.

**Comment by scaloni** [comment]
L'associazione carica-gruppo è bene non sia modificata finché non si implementa una procedura di rigenerazione dei dati di cache

**Comment by scaloni** [comment]
Il problema si presenta ancora.
Per esempio Cameruccio e Cicconi Massi sono passati il 21 novembre 2014 da NCD al gruppo misto (http://senigallia.openmunicipio.it/admin/people/groupcharge/) ma ancora il frontend li mostra le vecchie appartenenze:
http://senigallia.openmunicipio.it/institutions/groups/nuovo-centro-destra/
http://senigallia.openmunicipio.it/institutions/groups/gruppo-misto/

**Comment by scaloni** [comment]
Issue spostata in https://github.com/openmunicipio/om-senigallia/issues/45
