### ISSUE TITLE
Correggere il contenuto delle email di monitoraggio

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#405]
Nelle email di monitoraggio (se ne veda un esempio allegato):
- aggiungere il nome del mittente: "Open Municipio" (ora c'è solo l'indirizzo noreply@openmunicipio.it)
- localizzare la descrizione del politico/carica (es. "Maurizio Mangialardi - mayor");
- utilizzare il titolo aggiunto, se presente, al posto del titolo di un atto;
- aggiungere, prima del titolo dell'atto, anche il tipo di atto; per esempio: "Maurizio Mangialardi - Sindaco ha presentato la mozione Conferimento della cittadinanza onoraria..."
- nel footer della email, nel secondo paragrafo, rendere la frase "tuo profilo Open Municipio" un link alla pagina del profilo (per esempio http://senigallia.openmunicipio.it/users/profile/scaloni/)
- sostituire l'ultima riga con la seguente (aggiungendo i necessari link): Open Municipio è un progetto di Openpolis e InformaEtica, distribuito da InformaEtica, via Corinaldese, 52, 60019 Senigallia (AN) - tel. 071.7938239, info@informaetica.it

![gmail - monitoraggio open municipio](https://f.cloud.github.com/assets/799159/1075682/0156c246-14d3-11e3-918f-6c0f14e75cd1.png)

**Comment by fspegni** [comment]
vedi template in: open_municipio/open_municipio/newsletter/templates

**Comment by fspegni** [comment]
Mancano da implementare alcuni punti ... chiuso per errore ...

**Comment by fspegni** [comment]
RIsolto quasi tutto. Rimasti aperti questi due punti:
- tipo dell'atto prima del titolo
- titolo giornalistico al posto del titolo (per fare questo occorre rigenerare le news quando si setta (per la prima volta) il titolo giornalistico di un atto ... aprire ticket a parte)

**Comment by scaloni** [comment]
Sulla questione del titolo giornalistico è stato aperto il ticket #511

**Comment by scaloni** [comment]
Mi risulta che già ora una news viene generata se si setta titolo giornalistico (e/o tag?)
