### ISSUE TITLE
Installing requirements via "main.txt" file doesn't work

### ISSUE THREAD

**Issue by lorenzo-pasa** [openpolis/open_municipio#41]
Install the requirements via this terminal's command:
`pip install -r requirements/main.txt`
doesn't work.

It result in this error:
`Source in ~/.virtualenvs/open_municipio/build/django-model-utils has version 1.0.0.post that conflicts with django-model-utils==tip (from -r requirements/main.txt (line 3))`

The command at line 3 of the file [requirements/main.txt](https://github.com/openpolis/open_municipio/blob/dev/requirements/main.txt) is:

`````` django-model-utils==tip```
where "tip" means "the last version".

The error shown above interrupts the installation's flow, make it impossible to install all the requirements for open_municipio.

Oddly enough, installing django-model-utils via terminal's command:
```pip install django-model-utils==tip```
works perfectly.

(Obviously, the remaining requirements must be singly installed by terminal's command, or if you want to use the "file installation" method, you have to move the not-working line 3 to the bottom of the "main.txt" file)
``````

**Comment by seldon** [comment]
Just use the `--upgrade` flag when invoking `pip` from the command line:

```
 $ pip install --upgrade -r requirements/main.txt
```

Also note that `pip` has a nice [online documentation](http://pip.readthedocs.org/en/latest/usage.html#install-packages) ;-)

**Comment by lorenzo-pasa** [comment]
I tried with the `--upgrade` flag, but doesn't work.
It raises the same error, even if I try 
`pip uninstall django-model-utils` 
and then invoke
 `$ pip install --upgrade -r requirements/main.txt`

It seems like `pip` find an error at line 3 of the file "main.txt", but I can't see it ( if even there is it! ).
I think pip don't like the `==tip`

By the way, also Francesco and Diego had this problem, and he solved it by singly installing each main requirement via terminal's command.

**Comment by guglielmo** [comment]
The requirements/main.txt has been edited.
The line 

`````` django-model-utils==tip```
has been substituted with:
```-e git://github.com/carljm/django-model-utils.git#egg=django-model-utils```

The repository contain the source code of the _tip_ version, and the rest of our code works correctly.

This closes the issue.
``````
