### ISSUE TITLE
Ordinare le commissioni a cui un consigliere appartiene

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#414]
numerare da 1 a 6 le commissioni a cui appartiene un consigliere che siede in più di una 
es.
http://senigallia.openmunicipio.it/people/maurizio-perini-1977-08-03-senigallia/
oppure
http://senigallia.openmunicipio.it/people/roberto-mancini-1980-01-01/

**Comment by scaloni** [comment]
Credo sia lo stesso problema evidenziato nel ticket #370

**Comment by scaloni** [comment]
E' stato necessario riordinare le commissioni nella rispettiva tabella http://senigallia.openmunicipio.it/admin/people/institution/
