### ISSUE TITLE
allineamento foto poltici

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#424]
per una migliore impostazione grafica allineare le foto dei politici laddove compaiono ordinate in colonne, cioè sull'home page e su "politici" 
per esempio vedere l'allegato
![foto politici allineate](https://f.cloud.github.com/assets/4643590/1106208/40a7123e-193d-11e3-8750-e7b7a172e40a.JPG)

**Comment by scaloni** [comment]
In questo caso l'allineamento non è un requisito: la disposizione verticale delle foto dipende dal testo che le precede, che cambia da sezione a sezione

**Comment by giovaandrea** [comment]
Sì me n'ero accorto solo poi. In questo caso basterebbe fare un invio in fondo al testo de "i più monitorati"
