### ISSUE TITLE
Mancata notifica degli argomenti monitorati

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#428]
L'11 settembre 2013 è stata inserita l'interpellanza http://senigallia.openmunicipio.it/acts/interpellations/834/, contemporaneamente taggata con l'argomento "Urbanistica". La mattina successiva mi è arrivata la notifica dei monitoraggi (allegata qui sotto) ma quell'interpellanza non è presente nella mail, sebbene io stia già monitorando l'argomento "Urbanistica" (http://senigallia.openmunicipio.it/users/profile/scaloni/).

![gmail - monitoraggio open municipio](https://f.cloud.github.com/assets/799159/1128783/7bdf6bae-1b76-11e3-97dc-cfaad3030385.png)

**Comment by scaloni** [comment]
Lo stesso problema si è verificato per l'utente http://senigallia.openmunicipio.it/users/profile/limazzu/, che monitora l'argomento "Ambiente", con l'interpellanza http://senigallia.openmunicipio.it/acts/interpellations/837/, inserita l'11 settembre 2013 e taggata con l'argomento "Ambiente".

**Comment by guglielmo** [comment]
Va modificato il meccanismo di filtro su data per il fetch delle news legate agli atti taggati con l'argomento monitorato dall'utente.
Nel momento in cui l'atto è taggato, tutte le news generate dall'atto vanno modificate. Questo cambia il campo modified e permette di effettuare un fetch corretto.

**Comment by scaloni** [comment]
a regime il problema non dovrebbe sussistere se le mail vengono inviate 23 ore dopo l'import
da verificare

**Comment by fspegni** [comment]
testato e risolto
