### ISSUE TITLE
Errori nella pagina di Senigallia su Open Politici

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#432]
Il consigliere Elisabetta Allegrezza (http://senigallia.openmunicipio.it/admin/people/person/44) non è presente su Open Politici (http://politici.openpolis.it/localita/4396), dove invece compare un Marco Salustri (http://politici.openpolis.it/politico/marco-salustri/280054) che non è un politico di Senigallia.

**Comment by scaloni** [comment]
Il campo "ID politico in open polis:" presente nel modello person di OM corrisponde al numero finale nella URL di politici.openpolis.it?

Per esempio per http://politici.openpolis.it/politico/monica-antonacci/633758 l'ID da inserire in OM è 633758 ?

@guglielmo puoi aiutarci?

**Comment by fspegni** [comment]
Credo che sia inutile lasciare questo ticket aperto a questo punto.
