### ISSUE TITLE
Situazione patrimoniale di un politico

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#449]
Nella pagina di un politico, visualizzare un link verso la sua situazione patrimoniale.

Ciò può essere implementato semplicemente aggiungendo alle risorse di una person la nuova tipologia "informazioni finanziarie", evidenziata graficamente in modo opportuno (per esempio affiancandola al simbolo dell'euro) nella scheda del politico.

Si veda, a titolo indicativo, il wireframe allegato.

![politico](https://f.cloud.github.com/assets/799159/1244317/1d04fc4c-2a81-11e3-8cce-fa47cbf9a851.png)

**Comment by giovaandrea** [comment]
ok, ma a questo punto conviene anche fare un rimando ad una pagina con la "classifica" delle dichiarazioni di reddito.

**Comment by giovaandrea** [comment]
...e ne aggiungerei anche una sui dirigenti. Secondo me la trasparenza dev'essere sia politica che della macchina amministrativa visto che tutto viene finanziato con risorse pubbliche

**Comment by fspegni** [comment]
al momento la vista di dettaglio del politico carica una sola riga per ciascun tipo di risorsa. questo significa che se si inseriscono piu` record di tipo "informazioni finanziarie" solo uno di quelli viene mostrato
