### ISSUE TITLE
Lista degli interventi incompleta

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#452]
Nella pagina di ricerca degli interventi (per esempio http://senigallia.openmunicipio.it/acts/speech/?q=&person=simone-ceresoni-1968-06-10-corinaldo) vengono elencate solamente le sedute e non direttamente l'intervento.

Prevedere che ciascun elemento della lista abbia un testo siffatto:

```
Intervento n. x/totale "Titolo dell'intervento (se presente)"
"Titolo del SittingItem" della seduta di Consiglio Comunale n. 59 del 13/02/2013
```

e che tale testo contenga pertanto:
- un link diretto alla pagina dell'intervento
- un link alla pagina del SittingItem
- un link alla pagina della seduta

**Comment by fspegni** [comment]
aggiungere il link alla pagina del sitting item mi sembra che renda le tre righe di testo molto "pesanti" (tutte e tre blu, e non si capisce immediatamente la differenza fra le tre pagine -es la pagina del sitting item e quella del sitting sono concettualmente molto simili -, rischiando di cliccare sulla pagina indesiderata ...)

lascerei il link alla seduta e all'intervento solamente
