### ISSUE TITLE
Votazioni. Lista dei nomi passando sopra con il mouse

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#453]
http://senigallia.openmunicipio.it/votations/693/
Sulla destra, passando sopra con il mouse, devono comparire la lista dei nomi (e gruppo di appartenenza) dei 18 che hanno votato a favore, dei 4 contrari, dei 4 astenuti e del ribelle. Stile "mi piace" di fb

**Comment by scaloni** [comment]
@fspegni come è stato chiuso? non vedo differenze

**Comment by fspegni** [comment]
Devi passare col mouse sopra il "circoletto" col numero di Favorevoli, e
ti appare un tooltip col nome dei favorevoli ed il loro gruppo. Lo
stesso per i Contrari e gli Astenuti.
