### ISSUE TITLE
Inserire la data della risposta ad una interrogazione

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#462]
Nelle interrogazioni a risposta scritta prevedere un campo per la data della risposta.

**Comment by fspegni** [comment]
anziche' aggiungere un campo al modello, per il modello prevediamo una `property` che cerchi una transizione di tipo "risposta" e ne ritorni la data.

controllare anche l'admin delle Interrogazioni e delle Interpellanze, che al momento non mostra la tabella delle Transizioni

**Comment by scaloni** [comment]
Tenere presente anche https://github.com/openpolis/open_municipio/issues/566

**Comment by scaloni** [comment]
@fspegni si può chiudere?

**Comment by fspegni** [comment]
Se per te funziona bene così, si può chiudere
