### ISSUE TITLE
Link agli emendamenti non valido

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#472]
Nella pagina di ricerca degli atti (http://senigallia.openmunicipio.it/acts), filtrando il tipo "emendamento" (http://senigallia.openmunicipio.it/acts/?q=&selected_facets=act_type:emendamento) si ottiene una lista i cui elementi (per ora uno soltanto) puntano a "http://senigallia.openmunicipio.it/acts/None", pagina che restituisce un errore.

**Comment by fspegni** [comment]
ho corretto il link per rimandare alla pagina di tutti gli emendamenti dell'atto a cui si riferisce l'emendamento corrente.
emergono due problematiche:
- non esiste un link del singolo emendamento, al momento
- il tab con gli emendamenti di un atto mi sembra che non è stata neanche progettata, al momento

**Comment by scaloni** [comment]
C'è da completare la sezione degli emendamenti di un atto (per esempio http://senigallia.openmunicipio.it/acts/deliberations/217/amendments/)
