### ISSUE TITLE
ordinare le commissioni in ordine crescente, sia nella pagina commissioni che in quelle dei consiglieri pluriappartenenti

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#474]
Il ticket #414 e #370 risultano chiusi, ma i problemi persistono
http://senigallia.openmunicipio.it/people/maurizio-perini-1977-08-03-senigallia/
e
http://senigallia.openmunicipio.it/institutions/committees/

**Comment by scaloni** [comment]
I ticket #414 e #370 sono stati correttamente chiusi; è stato sufficiente riordinare le commissioni nella rispettiva tabella http://senigallia.openmunicipio.it/admin/people/institution/
