### ISSUE TITLE
Correggere le date riguardo ai capigruppo

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#475]
in questo caso risulta consigliere dal 16.11.2011, ma capogrupo Lega Nord dal 01.01.2008, idem per tutti gli altri
es. 
http://senigallia.openmunicipio.it/people/monica-antonacci-1965-08-08-fano/

**Comment by scaloni** [comment]
Confluito in https://github.com/openmunicipio/om-senigallia/issues/45
