### ISSUE TITLE
Mancato link nel collegamento atti-voto

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#481]
In una delibera di consiglio, una volta caricata in backend la votazione nella giusta transizione di stato, poi in front end non appare il link "votazione" ipertestuale. Ciò avviene solo se si preme la "x" a fianco della data si approvazione

**Comment by scaloni** [comment]
E' una regressione? Qualche settimana fa sembra che non ci facesse

**Comment by fspegni** [comment]
non capisco bene la descrizione del bug:
- succede con qualsiasi delibera o con una in particolare? aggiungi un link per favore a quella/e che ti da/nno problemi
- cosa avviene premendo la X a fianco della data (immagino nel front-end, giusto)?

cmq ho provato con questa delibera, ad es.

http://senigallia.openmunicipio.it/admin/acts/deliberation/164/ (back-end)

http://senigallia.openmunicipio.it/acts/deliberations/164/ (front-end)

e mi pare comportarsi correttamente

**Comment by giovaandrea** [comment]
In back end ho inserito la votazione relativa a questo atto
http://senigallia.openmunicipio.it/admin/acts/deliberation/1487/        backend

ma in front end, come puoi vedere, non compare la parola link "votazione" in blu. Se però clicchi la "x" nel quadro approvazione, quella a fianco alla data, essa compare (in questo caso specifico non l'ho fatto ma in altri casi sì.. così puoi provare tu e vedere l'esito)
http://senigallia.openmunicipio.it/acts/deliberations/1487/                  frontend

potrei non essermi spiegato bene, se vuoi possiamo sentirci su skype (giova.andrea@libero.it)

**Comment by fspegni** [comment]
il problema era legato ad un ordinamento errato delle transizioni di un atto (perche`arbitrario) nel metodo Act.get_last_transition . parte del problema sta nel fatto che le transizioni recano con se` solo la data di un "passo". tuttavia nello stesso giorno possono esserci molteplici passi (es. "presentato" e "approvato"). per ora ho "rafforzato" la logica ordinando le transizioni almeno per "id". questo significa che dovremmo assicurarci (in fase di importazione) di inserire la transizione di accettazione dopo quella di presentazione (per avere gli id ordinati in modo consistente).
