### ISSUE TITLE
Errato ordinamento numero atti per i politici

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#482]
Sia nella pagina dei consiglieri che dei membri di giunta se ordini la tabella "atti" non dà un ordine logico

http://senigallia.openmunicipio.it/institutions/council/

http://senigallia.openmunicipio.it/institutions/city-government/

**Comment by scaloni** [comment]
@fspegni Francesco, mi pare sia usato l'ordine lessicografico invece di quello strettamente numerico, lo stesso errore già fissato un altra volta

**Comment by giovaandrea** [comment]
Perdonami in anticipo @fspegni!  sarebbe molto comodo che in frontend rimanesse il filtro anche dopo aver cliccato sugli atti di un politico. Mi spiego, ordino i politici per numero di atti, clicco su uno qualsiasi della lista, torno alla pagina precedente ma non ho più memorizzato l'ordine crescente. Questo sia per il Consiglio che per la Giunta. grazie

**Comment by scaloni** [comment]
@giovaandrea Eventualmente crea un nuovo ticket, ma per la milestone Future
