### ISSUE TITLE
Declinare le pagine per Senigallia

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#487]
http://senigallia.openmunicipio.it/domande/

http://www.openmunicipio.it/aderire.html
"Per vedere Open municipio in funzione non c'è niente di meglio che navigare il sito di Udine" ... perchè quello di Senigallia no? ;-)

**Comment by fspegni** [comment]
chiudo il ticket perche`la pagian su openmunicipio non e` su questo repository
