### ISSUE TITLE
Committee vs commission: possible minor name conflict

### ISSUE THREAD

**Issue by ghost** [openpolis/open_municipio#49]
We use the name "commission" here:
https://github.com/openpolis/open_municipio/blob/dev/open_municipio/templates/people/institution_commission.html

and "committee" here:
https://github.com/openpolis/open_municipio/blob/dev/open_municipio/people/models.py#L310

Are we referring to the same institution? If so, please consider a standard naming.

**Comment by guglielmo** [comment]
The correct naming is Comitee (one T). So both are wrong. Will refactor the code as soon as possible.
