### ISSUE TITLE
Mantenimento filtro ordine del numero atti per politico

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#490]
Sulla pagina dei politici far mantenere il filtro anche dopo aver cliccato sugli atti di un politico. Mi spiego, ordino i politici per numero di atti, clicco su uno qualsiasi, torno alla pagina precedente ma non ho più memorizzato l'ordine crescente.
Questo sia per il Consiglio che per la Giunta.

http://senigallia.openmunicipio.it/institutions/council/
http://senigallia.openmunicipio.it/institutions/city-government/

**Comment by scaloni** [comment]
Duplicato di https://github.com/openpolis/open_municipio/issues/571
