### ISSUE TITLE
Rendere identificabili coloro che monitorano un politico

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#491]
Rendere visibili i "monitoranti" dei politici, rendendo ipertestuale il numero cittadini che monitorano il politico:
- nella pagina di un politico, a destra (es. http://senigallia.openmunicipio.it/people/maurizio-mangialardi-1964-11-17-ancona/)
- nella colonna "MONITORATO" della lista dei politici di Giunta (http://senigallia.openmunicipio.it/institutions/city-government/) o Consiglio (http://senigallia.openmunicipio.it/institutions/council/)

**Comment by scaloni** [comment]
Va progettata la vista, per visualizzare un gruppo di cittadini

**Comment by scaloni** [comment]
@vittorioa che ne pensi?

**Comment by scaloni** [comment]
Per il momento non lo consideriamo un requisito
