### ISSUE TITLE
Mancata ricerca atti per parola nei titoli giornalistici

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#492]
Es. delibera di giunta del 12 feb 2013
http://senigallia.openmunicipio.it/acts/cgdeliberations/380/
titolo atto:
Approvazione del regolamento per l'attribuzione degli incentivi per l'attivita' di accertamento dell'imposta comunale sugli immobili
titolo giornalisitco:
Modifica al regolamento per incentivi ai dipendenti comunali per accertamenti ICI

se la si cerca con le parole "modifica", "ici", "comunali" o "accertamenti" non compare. 
La si trova invece se si cerca "regolamento", "dipendenti", "incentivi", "accertamento"

**Comment by scaloni** [comment]
La parola ICI compare anche nel testo, ma nella forma apostrofata "nell'ICI"

**Comment by fspegni** [comment]
Anche questo atto dovrebbe comparire cercando "accertamenti", ma non viene trovato:

http://senigallia.openmunicipio.it/admin/acts/act/1111/

**Comment by fspegni** [comment]
notare che l'atto riportato da @scaloni non e' "trovabile" nel motore di ricerca atti anche restringendo la ricerca con le seguenti facets: 
- anno: 2012
- mese: febbraio
- tipo: delibera di giunta

es. http://senigallia.openmunicipio.it/acts/?q=&selected_facets=act_type%3Adelibera+di+giunta&selected_facets=pub_date%3A[2012-01-01T00%3A00%3A00Z+TO+2012-12-31T00%3A00%3A00Z]&selected_facets=month:febbraio

Probabilmente non viene aggiunto all'indice per qualche problema?

**Comment by scaloni** [comment]
Il commit https://github.com/openpolis/open_municipio/commit/9b2ad4f9729953c156ebe05eaa3f1c3d8189cd41 è stato successivamente sovrascritto, di fatto annullandolo.

**Comment by scaloni** [comment]
Ora le parole sono correttamente trovate. Puoi confermare @giovaandrea ?

**Comment by giovaandrea** [comment]
Yeah!
Ho fatto questa prova e sembra funzioni. Ho cercato la parola: "tosap"
http://senigallia.openmunicipio.it/acts/?q=tosap&person=
la delibera del CC del 30/7/2014, la quarta che compare, la trova nel titolo giornalistico (non c'era in quello ufficiale)

**Comment by fspegni** [comment]
ok. allora chiudo. grazie :)
