### ISSUE TITLE
Mandare email di monitoraggio solo se non vuote

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#494]
Le mail vanno mandate solo se contenenti eventi di monitoraggio da segnalare

**Comment by scaloni** [comment]
L'utente http://senigallia.openmunicipio.it/users/profile/giova.andrea/ ha ricevuto mail vuote il 12/11/2013 e il 17/11/2013

**Comment by fspegni** [comment]
questo problema capita(va) se qualcuna delle news aveva impostata una data None. ho modicato il metodo News.news_date per far si` che non ritorni mai None. fai ultima verifica dopo nuova importazione di atti

**Comment by fspegni** [comment]
risolto
