### ISSUE TITLE
Errore nel numero atti ricercati per argomento

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#496]
se si cerca per argomento, nella tabella compare un numero di atti superiore a quello effettivo riportato nella pagina con i risultati della ricerca. Questo mi sembra riguardi solo le delibere di giunta

es. ricerca "abusivismo edilizio", nella tabella compare n.8 atti
http://senigallia.openmunicipio.it/tags/abusivismo-edilizio/
ma nell'elenco sono in realtà 6
http://senigallia.openmunicipio.it/acts/?q=&tag=abusivismo-edilizio&selected_facets=act_type:delibera%20di%20giunta

nell'esempio specifico questa delibera di giunta è taggata con "abusivismo edilizio"
 http://senigallia.openmunicipio.it/acts/cgdeliberations/1320/
ma poi se cerco sotto argomenti/abusivismo edilizio è una di quelle che trova
http://senigallia.openmunicipio.it/acts/?q=&tag=abusivismo-edilizio&selected_facets=act_type:delibera%20di%20giunta

**Comment by scaloni** [comment]
Il problema descritto nell'esempio non è più presente; forse serviva una rigenerazione dell'indice Solr

@giovaandrea puoi verificare anche tu? Tieni conto che se metti il tag ad un atto, questo comparirà nei risultati di ricerca di quel tag solo il giorno successivo.

**Comment by giovaandrea** [comment]
Sì Risolto! Non sapevo che l'aggiornamento impiegasse 24h.
