### ISSUE TITLE
Problemi con la ricerca di parole accentate

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#497]
Nella pagina degli speech (http://senigallia.openmunicipio.it/acts/speech) la ricerca di parole accentate non produce alcun risultato.

Per esempio la parola "terzietà" è contenuta in almeno uno speech (http://senigallia.openmunicipio.it/acts/speech/1069/); la parola "libertà" è contenuta in diversi speech (per esempio, http://senigallia.openmunicipio.it/acts/speech/1884/).

Il problema non si presenta invece nella ricerca di atti (http://senigallia.openmunicipio.it/acts/?q=libert%C3%A0&person=).

**Comment by fspegni** [comment]
La differenza risiede nel fatto che negli speech le parole accentate sono memorizzate con la codifica html: es. `libertà` diventa `libert&agrave;`. Occorre allargare la ricerca in maniera da tornare anche il testo che contiene tali variazioni.
