### ISSUE TITLE
Aggiungere allegati di una interrogazione/interpellanza da backend

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#498]
L'interfaccia admin di una interrogazione (per esempio questa: http://senigallia.openmunicipio.it/admin/acts/interrogation/1588/) non consente di aggiungere allegati. Al momento, infatti, per aggiungere allegati si è obbligati ad agire sull'omologa scheda dell'atto generico (http://senigallia.openmunicipio.it/admin/acts/act/1588/).

**Comment by scaloni** [comment]
Estendere la patch anche alle interpellanze

**Comment by scaloni** [comment]
Provando ad aggiungere un allegato a questa interrogazione, si genera un errore e l'aggiunta non va a buon fine
http://senigallia.openmunicipio.it/admin/acts/interpellation/3223/

**Comment by scaloni** [comment]
In locale funziona, ma non sul server di produzione

**Comment by fspegni** [comment]
fixato momentaneamente modificando il file `/etc/apache/envvars`:

```
# Uncomment the following line to use the system default locale instead:
. /etc/default/locale

export LANG
```

assicurarsi che il file `/etc/default/locale` contenga un locale che finisca con `.UTF-8`. vedere come automatizzare questa configurazione (o una equivalente) negli script di deploy

**Comment by scaloni** [comment]
@fspegni gli script di deploy sono stati aggiornati? se si, chiudiamo il ticket
