### ISSUE TITLE
Errore nell'accesso ad alcuni atti da admin

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#499]
Si veda qui:
- http://senigallia.openmunicipio.it/admin/acts/agenda/212/
- http://senigallia.openmunicipio.it/admin/acts/agenda/211/
- http://senigallia.openmunicipio.it/admin/acts/agenda/30/
- http://senigallia.openmunicipio.it/admin/acts/agenda/1314/

**Comment by fspegni** [comment]
questi tag risultavano (sul db) associati a tag "None". non so di preciso come sia potuto succedere, mi sono venuti in mente 2 scenari:
- erano stati taggati con dei tag cancellati. qualcuno ha cancellato tag su senigallia? @scaloni  @giovaandrea?
- il sistema di tagging da frontend ha scaz#ato, inserendo un tag a None (mi pare strano non si sia notato prima)

cmq il problema non sembra dovuto all'aggiornamento di alcun pacchetto.

ho risolto il problema eliminando questi tag spuri a mano sul server, non chiudo il ticket perché  vorrei sapere da voi se il primo scenario è compatibile con qlc vs azione.

**Comment by scaloni** [comment]
Non posso escludere nessuna delle due possibilità.
Suggerisco di riprodurre la cancellazione di un tag associato ad un atto, e vediamo se rimane "None": faccio io?

**Comment by scaloni** [comment]
@fspegni verifichi anche l'errore nella migrazione del DB di ieri sera?

**Comment by fspegni** [comment]
Ok, procedi.

Ti suggerisco di fare cosi`:
- aggiungi un tag di prova
- tagga l'atto col tag di prova
- elimina il tag di prova
- accedi alla pagina di admin dell'atto

la situazioni con le migrazioni e` stata risolta

FS

Il giorno gio, 20/02/2014 alle 22.55 -0800, Marco Scaloni ha scritto:

**Comment by scaloni** [comment]
Ok, ho fatto la prova:
- ho aggiunto un tag "prova" (associato ad "Attività produttive" e "Ambiente")
- ho rigenerato l'indice Solr
- ho aggiunto il tag a http://senigallia.openmunicipio.it/acts/deliberations/1581/
- ho cancellato il tag, rispondendo si alla domanda:

```
Sicuro di voler cancellare Tag "prova"? Tutti i seguenti oggetti collegati verranno cancellati:
Tag: prova
Atto taggato: S-SG/2014/212 - APPROVAZIONE VERBALI SEDUTE PRECEDENTI (Approvazione verbali sedute precedenti) tagged in Attività produttive with prova
```

Aprendo l'atto non si presenta alcun errore: http://senigallia.openmunicipio.it/admin/acts/deliberation/1581/

**Comment by fspegni** [comment]
mumble mumble ... una cosa strana che ricordo e` che tutti gli atti
segnalati come problematici erano di tipo agenda.

sono importati o inseriti a mano? magari puoi ripetere la tua prova con
un atto di tipo agenda?

FS

Il giorno ven, 21/02/2014 alle 01.23 -0800, Marco Scaloni ha scritto:

**Comment by scaloni** [comment]
Ho riprovato con http://senigallia.openmunicipio.it/admin/acts/agenda/18/ ma funziona, il problema non si presenta.

**Comment by giovaandrea** [comment]
no, mai aggiunto nè tolto tag.

**Comment by fspegni** [comment]
per ora chiudo, senza aver capito bene dove fosse il problema. se tornasse il problema riapriamo.
