### ISSUE TITLE
IntegrityError salvando un atto da admin

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#501]
Salvando l'atto http://senigallia.openmunicipio.it/admin/acts/agenda/153/ si ottiene IntegrityError: "null value in column "category_id" violates not-null constraint"

**Comment by scaloni** [comment]
L'errore non si presenta, per esempio, qui: http://senigallia.openmunicipio.it/admin/acts/agenda/30/

**Comment by fspegni** [comment]
risolto smettendo di usare l'admin di default, e customizzando il fieldsets in AgendaAdmin

see  https://github.com/openpolis/open_municipio/commit/7420c51b33700747f7814f65cca1aea97392989b
