### ISSUE TITLE
Informazioni mancanti ed errori nell'aggiunta manuale di mozioni o ordini del giorno

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#502]
Aggiungendo manualmente una nuova mozione (http://senigallia.openmunicipio.it/admin/acts/motion/add/) o un nuovo ordine del giorno (http://senigallia.openmunicipio.it/admin/acts/agenda/add/), non è possibile impostare data, testo e istituzione emittente, e salvando si ottiene l'errore:

```
IntegrityError at /admin/acts/motion/add/
null value in column "emitting_institution_id" violates not-null constraint
```

**Comment by fspegni** [comment]
sono riuscito ad aggiungere sia una nuova mozione sia un nuovo odg. ho potuto settare tutti i campi menzionati, senza che comparisse l'errore. non ho dovuto fare nessuna modifica.

chiudo il ticket, ma se vedi che il problema rimane riaprilo con qualche dettaglio in piu`.
