### ISSUE TITLE
Incompletezze nella pagina admin di una delibera di Consiglio

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#503]
Nella pagina di una delibera di Consiglio (http://senigallia.openmunicipio.it/admin/acts/deliberation/add/) mancano i seguenti campi che sono invece presenti nella pagina di una delibera di Consiglio già inserita (per esempio http://senigallia.openmunicipio.it/admin/acts/deliberation/1581/)
- tag
- sottoscrittori
- allegati
- transizioni di stato
- emendamenti

**Comment by fspegni** [comment]
tolgo il priority-medium: al momento e` sufficiente fare "salva e continua le modifiche" per farli comparire
