### ISSUE TITLE
Eliminare la sezione emendamenti di una delibera di Giunta

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#504]
Nella pagina di admin:
- aggiungendone una manualmente: http://senigallia.openmunicipio.it/admin/acts/cgdeliberation/add/
- in una delibera già aggiunta, per esempio: http://senigallia.openmunicipio.it/admin/acts/cgdeliberation/1585/

**Comment by fspegni** [comment]
fatto

**Comment by scaloni** [comment]
@fspegni  devi deployare? ancora li vedo su http://senigallia.openmunicipio.it/

**Comment by fspegni** [comment]
si`, dovevo deployare
