### ISSUE TITLE
Incongrue statistiche sugli atti consiliari del Sindaco

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#505]
Nella pagina del Consiglio (http://senigallia.openmunicipio.it/institutions/council/) il numero di atti attribuiti al Sindaco (75) non coincide con quello complessivo ottenuto dai filtri (http://senigallia.openmunicipio.it/acts/?q=&person=maurizio-mangialardi-1964-11-17-ancona), per cui la somma degli atti di Consiglio (59 + 15 + 11 + 5) vale 90.

**Comment by fspegni** [comment]
un problema era il fatto che andavano "ripulite" le firme del sindaco (usando il nuovo comando. andrebbe inserito nel wiki di senigallia una procedura su come usare questo comando prima di avviare una import massiva). fatto quello, il divario passa da 75 vs 90 a 91 vs 90. capire perche`

**Comment by fspegni** [comment]
ok, il problema è che allo stato delle cose una delibera risulta firmata dal sindaco mangialardi, anziché dal consigliere:

http://senigallia.openmunicipio.it/admin/acts/act/167/

direi quindi che questo ticket puo` essere corretto a mano (segnalando a campanelli la firma errata, altrimenti re-importeremo la volta successiva ...)

**Comment by scaloni** [comment]
@fspegni non capisco, l'atto http://senigallia.openmunicipio.it/admin/acts/deliberation/167/ è una delibera di Consiglio, e rientra correttamente nei filtri di Mangialardi, la cui somma, per gli atti di Consiglio, fa 91; invece le statistiche della home page mostrano 90

**Comment by fspegni** [comment]
Il problema principale, e` che lo strumento di ricerca degli atti non
distingue quelli di Mangialardi-Consigliere da quelli di
Mangialardi-Sindaco. Per questo, facendo la ricerca degli atti di
Mangialardi, risultano 91 atti di consiglio firmati da
Mangialardi-Sindaco-o-Consigliere.

Il conto effettuato nella pagina del Consiglio, invece, considera i soli
atti di Mangialardi-Consigliere (91). 

Questo genera i due diversi numeri.

Quella delibera e`firmata dal Mangialardi-Sindaco. Se questo e`
corretto, allora non c'e` problema. Se invece doveva essere firmata dal
Mangialardi-Consigliere, allora va corretto il problema, a monte (nel
sistema informatico di Senigallia) o a valle (nei nostri dati).

Spero sia piu` chiaro il problema, ora.

Il giorno sab, 08/03/2014 alle 07.17 -0800, Marco Scaloni ha scritto:

**Comment by scaloni** [comment]
é chiaro @fspegni grazie; considero il ticket mio, da rigirare al Comune

**Comment by scaloni** [comment]
Il problema non sussiste, essendo lecito che Mangialardi firmi atti di consiglio in veste di Sindaco
