### ISSUE TITLE
Titolo atto chiave nella pagina del politico

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#507]
nella pagina del politico 
es. http://senigallia.openmunicipio.it/people/maurizio-mangialardi-1964-11-17-ancona/ 
nella tabella Atti chiave far comparire il titolo giornalistico dell'atto invece della data della seduta

**Comment by scaloni** [comment]
Intendi la tabella "Ultimi voti chiave"? In tal caso c'è già la colonna riservata all'atto, occorre fare in modo che sia popolata

**Comment by giovaandrea** [comment]
Sì mi riferivo a quella.

**Comment by scaloni** [comment]
@giovaandrea Vedi la colonna ATTO non popolata nei casi in cui il voto è collegato ad una trasizione di un atto?
