### ISSUE TITLE
Titolo giornalistico di un atto nelle relative votazioni

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#508]
Se una votazione è collegata ad un atto (direttamente o attraverso una sua transizione di stato), predisporre nella sua pagina (per esempio http://senigallia.openmunicipio.it/votations/1293/) un collegamento all'atto, attraverso il suo titolo che rimanda, attraverso un link, alla pagina dell'atto.

Il titolo dell'atto può essere inserito dopo quello già presente per il voto, evidenziato in modo differente e prefissato dalla stringa "Atto collegato:"

**Comment by scaloni** [comment]
@fspegni che ne pensi?
