### ISSUE TITLE
Ricerca dei politici limitata a quelli in carica

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#510]
La casella di ricerca del politico in home page (sotto il titolo: "Cosa fanno i tuoi rappresentanti?") deve pescare dall'intera lista di politici presenti in anagrafica, e non solamente da quelli attualmente in carica.

**Comment by giovaandrea** [comment]
Ok, ma c'è un problema direi redazionale, es. cerco Pazzani http://senigallia.openmunicipio.it/people/tiziano-pazzani-1968-07-21-senigallia/ da dove capisco che non è più consigliere? Il link a openpolitici non è quasi mai aggiornato
idem per 
http://senigallia.openmunicipio.it/people/monica-antonacci-1965-08-08-fano/
che ne dici @scaloni ?

**Comment by scaloni** [comment]
Concentrerei questa funzionalità in questo ticket: #442
