### ISSUE TITLE
Titolo giornalistico per le "Ultime attività dei cittadini" in home page

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#515]
In home page, nella sezione "Ultime attività dei cittadini", l'eventuale riferimento ad un atto visualizza il titolo originale e non quello giornalistico.

Si veda allegato
![2014-03-14_om-titolo-giornalistico-home](https://f.cloud.github.com/assets/799159/2418805/1885afa6-ab4e-11e3-949a-6884b745df2a.png)

**Comment by scaloni** [comment]
Il titolo originale a volte compare ancora
![om-ticket-515](https://cloud.githubusercontent.com/assets/799159/2955150/94eda956-da7c-11e3-926f-dc35780b03bf.png)

**Comment by fspegni** [comment]
Per le vecchie notizie non si possono cambiare le news (o almeno: al
momento non abbiamo un meccanismo per aggiornarle, ma c'e` un ticket
dedicato).

Per le nuove notizie: se il voto dell'utente avviene _prima_ che venga
impostato il titolo giornalistico, la notizia viene generata
(ovviamente) basandosi sul titolo originale. Se il voto avviene _dopo_
l'aggiunta del titolo giornalistico, allora la notizia riporta
quest'ultimo.

Finche`non gestiamo la ri-generazione delle news, questo e` il meglio
che possiamo fare, credo.
