### ISSUE TITLE
Sezioni mancanti nella pagina dei territori

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#524]
La correzione di #378 ha prodotto una pagina dei territori in cui manca la sezione per la condivisione e quella di monitoraggio.

**Comment by fspegni** [comment]
avevamo concordato che non ha senso monitorare e condividere la sezione dei territori, questo perche`tutti gli atti sono taggati con un territorio ... e cmq chi e` interessato a seguire gli atti taggati con un territorio e non gli altri? 

ricordo male?

**Comment by scaloni** [comment]
Concordo @fspegni
