### ISSUE TITLE
Gestione delle presenze di un politico

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#526]
E' necessario estendere il modello di OM perché vengano tracciate in modo completo le presenze dei politici alle Sitting delle Istitution alle quali partecipano.
Per esempio le presenze del Sindaco e degli assessori alle riunioni di Giunta al momento non sono tracciate. Le statistiche di presenza, infatti, valgono soltanto per chi ha diritto di voto in Consiglio e dunque si riferiscono esclusivamente ai voti espressi. Tutto ciò continuerà naturalmente ad essere tale e immutato. La mancanza che ci preme coprire riguarda in primis le presenze di Giunta.

La modifica prevede l'aggiunta dei modelli Attendance e ChargeAttendance, che tracciano le presenze in modo analogo a quanto rispettivamente Votation e ChargeVote tracciano i voti.

Una Attendance modella un "appello", cioè una conta delle presenze, per esempio una verifica del numero legale:
- è legata ad una Sitting (attraverso la quale si collega anche ad una Istitution)
- ha un elenco di ChargeAttendance
- può avere una data-ora
- può essere legata ad un Act

Con una ChargeAttendance si afferma che una data carica è presente/assente ad un appello, dunque:
- è legata ad una Attendance (attraverso la quale si collega anche ad una Sitting)
- ha uno stato (presente o assente)
- non ha una propria data-ora (ma eventualmente usa quella della Attendance).

Inoltre una Transition di un Act può avere una Attendance, così come già può avere una Votation.
In tal modo si afferma che un cambiamento nello stato di un atto (per esempio una delibera di Giunta) è avvenuto in presenza di alcuni assessori e non di altri. Ciò di fatto rappresenta il riassunto delle presenze pubblicato in una delibera di Giunta (per esempio inserito in forma tabellare in prima pagina qui: http://senigallia.openmunicipio.it/media/attached_documents/20140329/0005_GM_2014_40.rtf).

Una volta introdotto, i nuovi modelli potranno in futuro essere utilizzati per tracciare anche le presenze in altre Istitution, come le Commissioni o il Consiglio stesso (in sostituzione o, meglio, in aggiunta alle Votation).

Si allega schema dei modelli così emendati.
![omattendance](https://cloud.githubusercontent.com/assets/799159/2707287/20a145ea-c4a0-11e3-8799-59c794691c12.png)

**Comment by fspegni** [comment]
Una serie di domande puntuali per capire quando "simile" al modello Votation deve essere Attendance (tra parentesi c'è la risposta che darei):
- c'è un esito (approvato/respinto/...)? (sì)
- c'è una descrizione dell'atto (separata dal legame all'atto)? (è utile nel caso di importazione dati da un sistema informatico... per la presenza in giunta non credo che esista nessun sistema del genere, ma forse per le commissioni sì)
- ci sono i: numero legale, partecipanti, assenti, sì, ... ecc ? (forse farebbe comodo per modellare la partecipazione a sedute di commissioni e relative votazioni)
- c'è una distinzione fra un Attendance "chiave" ed una "non chiave"? (può fare comodo lasciarla, sempre pensando alle commissioni)
- ha senso parlare di Attendance di Gruppo, analogo al GroupVote? (no)
- ha senso parlare di ribelli? (no, perché non credo che abbia senso l'attendance di gruppo...)

Invito a rispondere in particolare @scaloni  e @guglielmo che hanno seguito il problema dall'inizio, ma qualsiasi opinione è benvenuta

**Comment by scaloni** [comment]
Una attendance modella un appello, cioè una conta delle presenze/assenze ad una seduta di qualche istituzione (Giunta, Consiglio, Commissioni).

Ecco le risposte che darei io:
- c'è un esito (approvato/respinto/...)? Intendi dire: c'è la maggioranza dei presenti? Non è essenziale saperlo, anche perché sarebbe un valore derivato (cache?). Un esito di tipo approvato/respinto non ha senso, non essendoci nulla, in un appello, da approvare o respingere.
- c'è una descrizione dell'atto (separata dal legame all'atto)? la prevederei come campo opzionale, nel caso sia esportato dal comune; al momento non sarà però riempito.
- ci sono i: numero legale, partecipanti, assenti, sì, ... ecc ? si
- c'è una distinzione fra un Attendance "chiave" ed una "non chiave"? (può fare comodo lasciarla, sempre pensando alle commissioni): si, ma non è essenziale; se ti viene comodo, meglio allora lasciarla.
- ha senso parlare di Attendance di Gruppo, analogo al GroupVote? forse ha senso, ma non è essenziale
- ha senso parlare di ribelli? no

**Comment by scaloni** [comment]
Nel frontend manca:
- il dettaglio delle presenze di una attendance
- il collegamento tra transizione dell'atto e attendance
