### ISSUE TITLE
Please remove spurious files from version control

### ISSUE THREAD

**Issue by seldon** [openpolis/open_municipio#53]
Francesco, I think you have the following files under revision control (Eclipse project's conf) :
- `.project`
- `.pydevproject`

If so, please remove those files from version control (using `git rm`), otherwise I canno't check out your branch without overwriting my own version of those files.

**Comment by fspegni** [comment]
I'll do it. btw, for the moment, if you are interested on the key-act / key-voting code, you find it in the pasa-dev branch (since Lorenzo p. and I worked on his branch, for the sake of simplicity)
