### ISSUE TITLE
Nome, cognome ed eventuale immagine nei commenti

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#530]
Attualmente appare il nickname se si pubblica un commento ad un atto
es. http://senigallia.openmunicipio.it/acts/cgdeliberations/3010/?c=3

**Comment by giovaandrea** [comment]
Nell'home page, sezione, Ultime attività dei cittadini, invece appare correttamente il nome e cognome. Ma l'atto non ha il titolo giornalistico

**Comment by scaloni** [comment]
Ancora non viene visualizzata l'immagine

**Comment by fspegni** [comment]
risolto
