### ISSUE TITLE
Prevedere slug per gli URL di atti, votazioni e speech

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#538]
Le URL di atti, votazioni e speech oggi drivano da ID interni. Renderle stabili e maggiormente indicizzabili, prevedendo delle slug composte da campi dei modelli.

**Comment by fspegni** [comment]
- le votazioni possono generare slug dalla seduta + idnum
- gli atti possono generare uno slug da idnum
- problema con alcune tipologie di atti che non prevedono idnum (Interrogation, Interpellation). come fare?
- le url memorizzate nelle news non possono essere cambiate (o almeno, non semplicemente). occorre mantenere in vita contemporaneamente le vecchie url (basate su pk degli atti) e le nuove url (basate su slug), per mantenere vive le url delle notizie (monitoraggi)

**Comment by joke2k** [comment]
Gli elementi per comporre uno slug potrebbero essere:
- data di produzione del documento
- numero incrementale basato sulla data (ogni giorno si riparte da 1)
- codice che identifica il tipo di documento (A: Atto, V: Votazione, N: News....)

20140921-1-A  è il primo documento (un atto) presentato il 21 settembre 2014.
20140921-2-V è il secondo documento (una votazione) fatta lo stesso giorno.

che ne pensate?

**Comment by fspegni** [comment]
la mia risposta alle domande di @joke2k 
- l'idea di includere la data è ok. piccolo problema nel caso della Votation: tale classe non prevede un campo data, ma si ottiene tramite il legame con una Sitting. questo legame è però opzionale. da modello quindi, potrebbero esistere Votation senza Sitting, e quindi senza data. forse dovremmo rendere il legame con la Sitting obbligatorio?
- il numero incrementale è difficile da gestire, perche` non esiste un campo simile nel db. oltretutto non è chiaro che significato abbia il fatto che un dato è "primo", "secondo", "terzo" di un giorno ... questo criterio (il numero ordinale) lo eviterei. userei piuttosto il campo idnum, già presente negli Act e nelle Votation.
- il codice che identifica il tipo di documento è ridondante: ogni istanza ha già una sua classe che ne descrive il tipo. oltretutto ogni url generata ha già un prefisso che lo distingue facilmente (es. /acts/deliberation/xyz, /votation/xyz, ...). anche questo criterio lo eviterei perciò

**Comment by scaloni** [comment]
Propongo:
- per gli atti, la combinazione di data, idnum e titolo (un po' come fa Wordpress)
- per le votazioni, data e idnum (ed eventualmente titolo dell'atto se collegato); renderei mandatorio il campo Votation.sitting, senza il quale la votazione è decontestualizzata (mancherebbe addirittura l'istituzione nella quale si vota)

**Comment by scaloni** [comment]
@fspegni è normale quella serie di zeri dopo la datanell'URL?
http://senigallia.openmunicipio.it/acts/cgdeliberations/2014-08-26-000000-s-sg-2014-1493-concessione-contributo-alla-croce-rossa-italiana-comitato-locale-di-senigallia-per-deposito-e-custodia-di-attrezzature-e-automezzi-destinati-al-servizio-di-protezione-civile/
