### ISSUE TITLE
Events app and calendar widget

### ISSUE THREAD

**Issue by ghost** [openpolis/open_municipio#54]
Events app must pass event dates to the template so that a calendar widget can be populated. The format for such dates must be defined. The time range for such dates must be defined too: past events will appear on the calendar from the beginning of time?

**Comment by joke2k** [comment]
My idea is to display the calendar using the [jquery-ui.datepicker](http://jqueryui.com/demos/datepicker/) and readjust to view events: http://jsfiddle.net/Zrz9t/2/
so we could use all the features offered by the plugin.

Assuming that [all necessary](https://github.com/openpolis/open_municipio/blob/dev/open_municipio/templates/taxonomy/topic_detail.html#173) is loaded, we can populate it like this:

```
<div class="calendar" data-calendar=".calendar_events"></div>
..
<ul class="calendar_events">
   <li data-day="MM/DD/YYYY">event text</li>
   ...
</ul>
```

as in [taxonomy/topic_detail.html#35](https://github.com/openpolis/open_municipio/blob/dev/open_municipio/templates/taxonomy/topic_detail.html#35).

The calendar will show all past events from a month ago.

For now the click shows an alert, in the future will scroll the list of events ... admitted that there will be something to scroll.

**Comment by ghost** [comment]
Should I also add some javascript code with some event listing?

**Comment by joke2k** [comment]
you should not, only the _data-day_ attribute for every **li** in **ul.calendar_events**.

**Comment by ghost** [comment]
This [0] should do the trick then. Let me know if some modification is needed. AFAIAC this is closed.

[0] https://github.com/openpolis/open_municipio/blob/0e9d34adc3e95563b039fa0350fa8c0c77b16dab/open_municipio/templates/people/institution_citygov.html#L27
