### ISSUE TITLE
Avviso del vaglio redazionale sui commenti agli atti degli utenti

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#542]
Dovremmo aggiungere un "?" o simile affianco a "commenti" dove spieghiamo in 2 righe il regolamento per poter aggiungere un commento, tipo:
"La Redazione si riserva la possibilità di omettere termini o commenti che risultino impropi o offensivi"

**Comment by scaloni** [comment]
Il contenuto della spiegazione potrebbe riprendere quanto presente qui (al punto 6): http://senigallia.openmunicipio.it/regolamento/

**Comment by fspegni** [comment]
aggiungere alle etichette "commenti" di atti e votazioni (vista dettaglio)
