### ISSUE TITLE
Atto generico restituisce errore

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#544]
http://senigallia.openmunicipio.it/admin/acts/act/3327/
http://senigallia.openmunicipio.it/admin/acts/act/3314/
http://senigallia.openmunicipio.it/admin/acts/act/3334/

mentre invece funzionano i link specifici, ad esempio http://senigallia.openmunicipio.it/admin/acts/deliberation/3327/

**Comment by fspegni** [comment]
non potendo replicare il bug, per il momento chiudo la issue
