### ISSUE TITLE
Impossibile visualizzare la scheda dei voti collegati ad un atto

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#546]
Si veda qui:
http://senigallia.openmunicipio.it/acts/amendments/3140/

cliccando sulla scheda dei voti ("1 Voto"), si ottiene un errore, come se la URL (http://senigallia.openmunicipio.it/votations/?act_url=/acts/amendments/2011-04-18-s-sg-2013-2202-emendamento-1-delibera-44/) fosse errata, e comunque non funzionasse la ricerca delle votazioni con il filtro act_url.
Non si ottiene errore, bensì un risultato vuoto, se si cambia la URL dell'atto, sostituendo l'id allo slug: http://senigallia.openmunicipio.it/votations/?act_url=/acts/amendments/3140/

**Comment by fspegni** [comment]
il problema e' legato alla regexp dell'url:

# 

ValueError at /votations/

invalid literal for int() with base 10:

# '2011-04-18-s-sg-2013-2202-emendamento-1-delibera-44'

credo di poterla correggere nei prox giorni.

**Comment by fspegni** [comment]
ok, anche se al momento il problema e` "nascosto", ho fatto un po' di debug aggiuntivo: le righe problematiche sono le seguenti:

```
        if self.request.GET.get("act_url"):

            act_id = int(self.request.GET.get('act_url').split("/")[-2])

    ...

            extra['act_votations'] = True

            extra['act'] = Act.objects.get(pk=act_id).downcast()
```

dentro `
/home/open_municipio/senigallia.openmunicipio.it/private/venv/src/open-municipio/open_municipio/votations/views.py` (riga 113). 

il codice si aspetta che quello passato sia l'id dell'atto, e quindi fa il cast ad int(...). ovviamente se gli passiamo lo slug, questo codice si "rompe". 

suggerisco quindi di non usare il metodo get_short_url(...): cosi' si producono ancora url artificiose, annullando di fatto il beneficio di avere url "naturali", sfruttando lo slug. 

la mia proposta e': facciamo passare la presentazione a senigallia, e poi correggo il codice della vista per supportare sia le url basate su pk che quelle basate su slug + eliminiamo il metodo get_short_url(...) (che mi pare sia stato creato da @scaloni solo a questo scopo (sbaglio?)

**Comment by scaloni** [comment]
Ok. Comunque il link che usa get_short_url è interno, e secondo me può anche andar bene in quel contesto.

**Comment by fspegni** [comment]
il problema mi sembra risolto
