### ISSUE TITLE
Pagina di errore senza grafica

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#547]
Mancano immagini e stili grafici
![pagina-di-errore-senza-grafica](https://cloud.githubusercontent.com/assets/799159/4689041/eb664470-56a3-11e4-8c78-ec5f505d8caa.png)

**Comment by fspegni** [comment]
la pagina si visualizza correttamente se invocata "direttamente" dall'url:

http://senigallia.openmunicipio.it/500/

segnalate una url che genera la pagina di errore senza grafica, in modo da poter debuggare il problema

**Comment by scaloni** [comment]
Questa presenta il problema
http://senigallia.openmunicipio.it/users/profile/
