### ISSUE TITLE
Input field for comments; send button or enter key

### ISSUE THREAD

**Issue by ghost** [openpolis/open_municipio#55]
Users post their comments through a text box. Is that box supposed to be an input field or a text area?

Are comments sent by clicking a "Send" button or when "Enter" key is pressed?

**Comment by guglielmo** [comment]
Comments should be written inside a textarea. There must be a "send" button, and comments are sent when the user pushes the button. Pressing "enter" creates a new line in the text area, expanding it to contain the text.

The text area input field can be set to 4 lines of height. It will be resized automatically by javascript.
