### ISSUE TITLE
Foto di un utente politico ricavata dalla carica

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#554]
Nel caso in cui un utente corrisponda ad una Person, in assenza di una immagine caricata dall'utente, utilizzare quella del profilo.

Si veda ad esempio:
http://senigallia.openmunicipio.it/users/profile/MaurizioSalustri/

**Comment by scaloni** [comment]
@fspegni mi risulta chiuso, giusto?

**Comment by fspegni** [comment]
si': prima viene cercata l'immagine della persona. se presente si mostra quella, altrimenti si mostra l'immagine del profilo (se presente)
