### ISSUE TITLE
Nuovi stati finali di un atto

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#555]
Aggiungere, a tutti gli atti di Consiglio (Deliberation, Interrogation, Interpellation, Motion, Agenda, Amendment) i seguenti due ulteriori stati finali (quindi appartenenti anche a FINAL_STATUSES):
- RETIRED
- DECAYED
- POSTPONED

Per ogni atto, prevedere un metodo (@property ?) che indichi se l'atto è in uno stato finale positivo o negativo, essendo più di uno gli stati con esito negativo.

**Comment by scaloni** [comment]
Gli stati finali negativi potrebbero essere elencati in una ulteriore tupla analoga a FINAL_STATUSES ?

**Comment by scaloni** [comment]
Aggiornato lo schema XML
https://github.com/openpolis/open_municipio/commit/3e30844a1e45dc8793ae03eb735e054b493bc877

**Comment by fspegni** [comment]
si e' stabilito di non implementare la property

**Comment by scaloni** [comment]
Dimenticavo lo stato "POSTPONED"

**Comment by scaloni** [comment]
Nelle news, il testo non viene popolato con il valore dello stato, invece comare:
L'atto xxx è in uno stato non determinabile
