### ISSUE TITLE
Migliorare l'HTML dei commenti

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#560]
Per esempio vedere questo commento:
http://senigallia.openmunicipio.it/admin/om_comments/commentwithmood/28/
che contiene link e righe che vanno a capo, ma che viene reso come testo semplice, senza andare mai a capo:
http://senigallia.openmunicipio.it/acts/cgdeliberations/3692/

**Comment by scaloni** [comment]
La pagina dell'atto con quel commento non si apre più
http://senigallia.openmunicipio.it/acts/cgdeliberations/2014-11-04-000000-s-lp-2014-2048-concessione-gestione-e-manutenzione-degli-impianti-di-pubblica-illuminazione-e-semaforici-realizzazione-di-interventi-di-adeguamento-normativo-ed-efficientamento-energetico-finanza-di-progetto-nei-servizi-ai-sensi-dellart-278-del-dpr-2072010-attuazione/

**Comment by fspegni** [comment]
avevo introdotto un errore, che ho risolto con l'ultimo commit. infatti ora la pagina col commento si riapre. ri-chiudo
