### ISSUE TITLE
Errato link all'atto collegato alla votazione

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#561]
Nella ricerca delle votazioni (http://senigallia.openmunicipio.it/votations/) il link all'atto, qualora presente, non è corretto.

Per esempio: http://senigallia.openmunicipio.it/votations/[u'/acts/deliberations/3669/']

**Comment by fspegni** [comment]
effettivamente, come ha ipotizzato @scaloni , la presenza di un altro indice con campo `act_url` impostato a MultiValueField, richiede che anche in `VotationIndex` il campo `act_url` sia dello stesso tipo. Occorre correggere la generazione dell'indice (deve ritornare un insieme), ed il template (nel caso delle votazioni, si tratta sempre di un insieme con un solo elemento, quindi nel template mostreremo il primo atto dell'insieme `result.act_url`)
