### ISSUE TITLE
Notifiche dei commenti verso chi monitora l'oggetto

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#562]
Chi monitora un oggetto (per esempio un atto) al quale sono associati commenti, viene notificato della presenza di nuovi commenti.

**Comment by scaloni** [comment]
Per esempio, per gli atti sono sufficienti le news di tipo community di priorità 1
http://senigallia.openmunicipio.it/admin/newscache/news/?priority=1&generating_content_type=17&news_type__exact=COMM

**Comment by fspegni** [comment]
al momento selezionando le news di tipo community con priorita' 1 si ottengono anche notizie come "X ha iniziato a monitorare Y". 

soluzione proposta: rendere quest'ultimo tipo di notizie di priorita' 2, in modo da escluderle dalla selezione
