### ISSUE TITLE
Impossibile chiudere una interrogazione su admin dell'atto specifico

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#566]
Per esempio da qui non si può chiude l'atto (il frontend valuta il flag status_is_final)
http://senigallia.openmunicipio.it/admin/acts/interrogation/3721/

E si è obbligato a settarlo qui:
http://senigallia.openmunicipio.it/admin/acts/act/3721/

Inoltre nell'admin dell'atto generico la lista dei possibili stati di una transazione di una interrogazione/interpellanza non è quella corretta, sembra quella di una delibera
Sebbene sopra la combo sia mostrato lo stato corretto: "PRESENTED il 2014-11-13" oppure "ANSWERED il 2014-11-24"

**Comment by scaloni** [comment]
Se è il caso, prevedere la gestione delle transizioni, che ora non sono editabili sull'admin dell'atto specifico

**Comment by fspegni** [comment]
@scaloni  dovrebbe essere risolto. Puoi verificare?
