### ISSUE TITLE
Impossibile aggiungere una interrogazione da admin

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#576]
http://senigallia.openmunicipio.it/admin/acts/interrogation/add/

Riprodotto in locale, l'errore è

```
AttributeError at /admin/acts/interrogation/add/
'NoneType' object has no attribute 'downcast'
```

**Comment by fspegni** [comment]
ho potuto riscontrare il problema la prima volta che ho caricato la pagina. il problema non si presentava eseguendo `django-admin.py runserver` in locale. ho quindi attivato il debug in produzione (`DEBUG = True` e `TEMPLATE_DEBUG = True`) e riavviato apache. il problema e' scomparso. ho quindi reimpostato `DEBUG = False` e `TEMPLATE_DEBUG = False` ed il problema ora non si ripete.

chiaramente se c'era un problema o si e' "magicamente" risolto, o rimane latente e si manifestera' nuovamente. chiudo il bug perche' ora non si manifesta. lo riapriremo se dovesse ripresentarsi.

**Comment by scaloni** [comment]
In locale, la prima volta che ho aperto la pagina di aggiunta interrogazione non ho avuto il problema, ma si verifica sempre dopo che ne aggiungo una

**Comment by fspegni** [comment]
duplicate of #586
