### ISSUE TITLE
On comment success...

### ISSUE THREAD

**Issue by ghost** [openpolis/open_municipio#58]
Where is user redirected after successfully posting a new comment? As of now, that's just a "Thanks for your comment" on blank page.

**Comment by guglielmo** [comment]
After a comment is succesfully posted, the user is redirected to the page where the comment was inserted, so that he can read the list of comments, with his comment on top.

A flash message is displayed on the top of the page 
(https://docs.djangoproject.com/en/dev/ref/contrib/messages/),
that tells the user that his message was inserted correctly.

In the view:

```
from django.contrib import messages
...
messages.success(request, _('Your comment was accepted'))
```

In the template:

```
{% block alerts %}
{% if messages %}
  <div class="container" style="margin-top: 1em">
    {% for message in messages %}
      <div class="row">        
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{%else %} class="alert"{% endif %}>
          <strong>Attenzione!</strong>
          {{ message }}
        </div>
      </div>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}
```

**Comment by ghost** [comment]
Default order is first comments on top, latest comments at the bottom. To revert this we need https://bitbucket.org/ubernostrum/django-template-utils
Should we go for it or get stuck with default ordering?

**Comment by ghost** [comment]
As for the message "Your comment was accepted", my understand is that including it into comments (or our om_comments version) would imply some monkey patching. I might be wrong, but I see some alternatives.

I would rather take advantage of the comment_TTL custom filter which tells us how old a comment is. We could show a "Your comment was accepted" message for as long as the comment removal button is shown.

A second alternative is using signals to trigger a "show success message" event after post_comment succeeds.
