### ISSUE TITLE
Link diretto alla votazione da etichetta atto

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#584]
cliccando sull'etichetta "approvato", "in esame", "Respinto" ecc... mi rimanda alla relativa pagina col dettaglio della votazione
es. qui:
http://senigallia.openmunicipio.it/acts/

**Comment by fspegni** [comment]
Nota che il link alla votazione puo' essere aggiunto solo se si trova nello stato "approvato" o "respinto". Negli altri casi non viene aggiunto nessun link. Controllare che sia il comportamento desiderato. @giovaandrea @scaloni

**Comment by scaloni** [comment]
Ok!

**Comment by giovaandrea** [comment]
Vogliamo considerare anche il caso "posticipato"?
