### ISSUE TITLE
Adeguamento alla nuova normativa sui cookie

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#588]
http://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/3167231

**Comment by fspegni** [comment]
Se ricordo bene noi facciamo uso del solo Google Analytics, quale servizio basato su cookies (e forse Django ne installa di propri, per gestire le sessioni dell'utente). Credo che quindi ricadiamo nel caso "Google Analytics" in questo link:

http://www.agendadigitale.eu/competenze-digitali/cookie-law-che-fare-se-utilizziamo-google-analytics-e-adsense_1549.htm
-  banner semplificato all'apertura tramite il quale:
  a) si avverte che il sito fa uso di cookie tecnici per ricordare la scelta dell'utente, 
  b) si avverte che il sito consente anche l'invio di cookie di terze parti, 
  c) si indica il link all'informativa completa  
  d) si comunica che comunque è possibile scegliere di non autorizzare i cookie di analisi tramite il sito del terzo.
- informativa completa tramite la quale si devono rendere tutte le informazioni ex art. 13 Codice Privacy (necessarie solo per il cookie tecnico installato) nonché le informazioni relative al link all'informativa privacy di Google Analytics.

Non so se abbiamo pronte le "informative complete" (ns e di Google Analytics)

**Comment by scaloni** [comment]
Si credo anche io che ricadiamo nell'obbligo, seppure nella versione ridotta, visto che non facciamo profilazione degli utenti.

Un eventuale banner credo che:
- debba essere ad ingombro ridotto, penso soprattutto alla versione mobile;
- debba tenere conto delle precedenti accettazioni dello stesso utente, sia che questo sia registrato (nuovo apposito flag nel modello?) sia che non sia registrato (tramite cookie)

Che ne pensi @fspegni ?

**Comment by fspegni** [comment]
Ho trovato questa app riutilizzabile che sembra adeguata: https://github.com/TyMaszWeb/django-cookie-law

**Comment by scaloni** [comment]
@fspegni una volta che l'utente ha accettato il warning, il banner viene mostrato in successive navigazioni dello stesso utente?

**Comment by fspegni** [comment]
No, tramite un cookie di memorizza là scelta dell'utente (per un tot di
giorni). Volendo si potrebbe modificare il modello UserProfile per
memorizzare la scelta nel db e non mostrare più il banner, però
personalmente eviterei di sporcare il modello per questo scopo
Il 03/Nov/2015 08:59, "Marco Scaloni" notifications@github.com ha scritto:

**Comment by scaloni** [comment]
Allungherei di molto il numero di giorni; c'è un massimo?

**Comment by fspegni** [comment]
Per legge mi sembra di no. L'app di default mi pare che faccia scadere il
cookie dopo 1000 gg. verifico meglio
Il 03/Nov/2015 10:05, "Marco Scaloni" notifications@github.com ha scritto:
