### ISSUE TITLE
Pagine di Consiglio e Giunta mostrano vecchie cariche

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#593]
Dopo il passaggio di consiliatura, sono state modificate tutte le vecchie cariche (ponendo end_date al 21/06/2015) e contemporaneamente create nuove InstitutionCharge con start_date al 22/06/2015:
- una per il sindaco
- 7 per gli assessori
- 25 per i consiglieri

Tuttavia sia la pagina della Giunta (http://senigallia.openmunicipio.it/institutions/city-government/) sia quella del Consiglio (http://senigallia.openmunicipio.it/institutions/council/) mostrano ancora le vecchie cariche.

**Comment by fspegni** [comment]
era solo una questione di cache. risolto riavviando il servizio
