### ISSUE TITLE
Sezione "Argomenti di cui si occupa" vuota

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#595]
Nella pagina di un politico
Ad esempio http://senigallia.openmunicipio.it/people/simeone-sardella-1973-01-15-ancona/

**Comment by fspegni** [comment]
Ho notato che quel blocco si riferisce agli atti della carica piu' recente per il politico in questione. Vedo due possibili soluzioni:
- facciamo in modo che quel blocco visualizzi l'unione di tutti gli argomenti trattati da tutte le cariche che afferiscono alla persona
- spostiamo quel blocco nella parte di pagina riferita alla carica specifica

Io propendo per la prima soluzione

**Comment by scaloni** [comment]
Anche io, meglio considerare l'insieme delle cariche di una stessa persona

**Comment by scaloni** [comment]
Perfetto. Meglio ancora farci una tag cloud, vedi https://github.com/openpolis/open_municipio/issues/601
