### ISSUE TITLE
Valore nullo per l'indicatore della media delle presenze o assenze

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#596]
Nella pagina di una carica, anche passata.
Ad esempio: http://senigallia.openmunicipio.it/people/simeone-sardella-1973-01-15-ancona/consiglio-comunale-2010-4-14/

**Comment by fspegni** [comment]
Ho replicato il problema in locale (perche' alla url postata ormai la media e' diversa da 0). Qual e' il problema? Vedo correttamente indicato che il consigliere aveva 0 presente, ed una media di 0% (sia per presenze che per assenze). Mi pare corretto pero'. Cosa mi perdo?
