### ISSUE TITLE
Sezione "Atti su cui lavora" invariata rispetto alla carica

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#600]
E' identica per le due cariche di sindaco: quella vecchia di Mangialardi (http://senigallia.openmunicipio.it/people/maurizio-mangialardi-1964-11-17-ancona/sindaco-2010-4-14/) ha la stessa lista di quella nuova (http://senigallia.openmunicipio.it/people/maurizio-mangialardi-1964-11-17-ancona/sindaco-2015-6-22/), e gli atti elencati sono riferiti alla carica corrente.

**Comment by fspegni** [comment]
gia' risolto in un commit  che non avevo ancora pushato e deployato. ora la modifica e' visibile sul server
