### ISSUE TITLE
User votes interaction

### ISSUE THREAD

**Issue by guglielmo** [openpolis/open_municipio#61]
When an authenticated user hovers on the voting box:
- the cursor takes the form of a pointer to a link, both on the little hands and on the text 
- the "Sono favorevole" or "Sono contrario" texts are link
- a title attribute must describe the effects the user gets when pressing the button:
  - click to vote for / click to retire your vote
  - click to vote against / click to retire your vote
- the little hand must be colored (green or red) when the user has voted for / against
- the color of the little hand when the user hovers on it must be black, if the effect of clicking is to retire the vote

**Comment by ghost** [comment]
- the cursor takes the form of a pointer to a link, both on the little hands and on the text
  That's a no brainer, adding `th.vote { cursor: pointer; }` to `/open_municipio/less/site.less` will do the trick
- the "Sono favorevole" or "Sono contrario" texts are link
  Why? Are we concerned about non-javascript users?
- a title attribute must describe the effects the user gets when pressing the button
  This can be achieved with bootstrap tooltips, applied on th.up-voted, th.down-voted or th.vote
- the little hand must be colored (green or red) when the user has voted for / against
  Again, we could take advantage of th.up-voted and th.down-voted classes, which we already use within voting.js
- the color of the little hand when the user hovers on it must be black, if the effect of clicking is to retire the vote
  th.vote

**Comment by seldon** [comment]
This issue no longer applies to our codebase, since the client-side voting widget has undergone a full redesign.
