### ISSUE TITLE
Il numero di atti presentati dai consiglieri e' inconsistente

### ISSUE THREAD

**Issue by fspegni** [openpolis/open_municipio#618]
Talvolta accade che in home i consiglieri con piu' atti, abbiano un numero di atti diverso da quello riportato nella colonna della pagina dei consiglieri (es. http://senigallia.openmunicipio.it/institutions/council/ )

Il problema capita perche' la query in home page e':

```
        context['most_acts'] = counselors.\
            filter(actsupport__support_type=ActSupport.SUPPORT_TYPE.first_signer).\
            filter(start_date__lte=today).filter(Q(end_date=None) | Q(end_date__gte=today)).\
            annotate(n_acts=Count('actsupport')).order_by('-n_acts')[0:3]
```

mentre nella pagina dei consiglieri si stampa l'attributo `.presented_acts.count()` (senza distinguere in base al `ActSupport.SUPPORT_TYPE`.

Soluzione: calcolare il numero di atti presentati da un consigliere senza distinguere fra primo firmatario e co-firmatario.

**Comment by giovaandrea** [comment]
Vedo che ora non c'è più discrepanza tra home e la pagina consiglio, ma c'è con la pagina politici
http://senigallia.openmunicipio.it/people/

**Comment by fspegni** [comment]
Fixed
