### ISSUE TITLE
Rendere obbligatorio l'indirizzo IP nell'inserimento di un commento

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#627]
Quando si inserisce un commento in back end il comanda Salva non funziona se non si inserisce anche l'indirizzo IP.
Per rendere intuibile l'obbligatorietà scrivere in grassetto anche il campo "Indirizzo IP:"

http://senigallia.openmunicipio.it/admin/om_comments/commentwithmood/add/

**Comment by soujiro86** [comment]
@fspegni Ciao Francesco, mi chiedevo: Se l'ip è quello dello stesso amministratore che aggiunge l'oggetto, non è meglio inserire dinamicamente dalla logica l'indirizzo IP ?
