### ISSUE TITLE
Calcolare automaticamente la dimensione degli allegati

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#633]
Al momento il campo viene popolato manualmente

Si veda ad esempio:
http://senigallia.openmunicipio.it/acts/interrogations/2017-02-06-richiesta-verifica-palestra-marchetti-aprte-esterna/documents/

**Comment by giovaandrea** [comment]
Perchè è stato chiuso questo ticket?
Tutt'ora in front end non compare
http://senigallia.openmunicipio.it/acts/interrogations/2017-02-06-richiesta-verifica-palestra-marchetti-aprte-esterna/documents/
