### ISSUE TITLE
Nessun conteggio accesso agli atti nella pagina dei consiglieri

### ISSUE THREAD

**Issue by giovaandrea** [openpolis/open_municipio#640]
Sotto la sezione atti presentati compare il corretto numero di accesso agli atti nella pagina people (in basso a dx)
http://senigallia.openmunicipio.it/people/

mentre compare 0 nella pagina dei consiglieri, sempre in basso a dx (nonostante in admin viene popolato il campo "istituzione"con consiglio comunale)
http://senigallia.openmunicipio.it/institutions/council/

**Comment by fspegni** [comment]
Questo e` un errore di importazione dei dati a Senigallia. In particolare gli accessi agli atti non erano legati all'istituzione Consiglio Comunale. Lascio questo ticket aperto come promemoria per modificare il codice e impostare automaticamente l'istituzione CC in fase di salvataggio di un accesso agli atti da admin.
