### ISSUE TITLE
Acts vs ``get_absolute_url`` 

### ISSUE THREAD

**Issue by ghost** [openpolis/open_municipio#65]
There are times when you want to retrieve one act's url even if you don't know what kind of act it really is (motion, deliberation, ...).

At the moment this doesn't seem possible.

Eg: when looping over events in institution templates we have:

```
{% for event in events %}
<li><strong>{{ event.date|date:"d.m.Y" }}</strong> <a href="{{ event.act.get_absolute_url }}">{{ event.act.title }}</a></li>
{% endfor %}
```

`get_absolute_url` seems to be broken here.

**Comment by ghost** [comment]
It looks like we are in this scenario, aren't we?

http://stackoverflow.com/questions/3176731/django-inheritance-and-permalinks

**Comment by seldon** [comment]
You are right, Fabio.  The approach I would suggest is:
- define a proper `get_absolute_url()` method for each `Act`subclass (`Deliberation`, `Motion`, etc.)
- within the template, replace `event.act.get_absolute_url` with `event.act.downcast.get_absolute_url`
