### ISSUE TITLE
Correct file "solr_haystack.rst"

### ISSUE THREAD

**Issue by lorenzo-pasa** [openpolis/open_municipio#86]
In **open_municipio / docs / dev /**  folder,  the file **"solr_haystack.rst"** doesn't  show correctly the "code" sections.
Actually, they aren't shown at all. 
For example, in the "Solr installation" and "Haystack configuration" sections (line 51 and 86) the code is not shown.
**Seems like the problem are the formatting "sourcecode::python" and  "sourcecode::bash" instructions.**

The only way to see the code (and so correctly finish the installation process) seems to be to switch to RAW view of the file.

**Comment by seldon** [comment]
Works for me. Are you sure that you are correctly regenerating HTML docs (using `make html` ?)

**Comment by seldon** [comment]
Anyone else does confirm this issue ?

**Comment by lorenzo-pasa** [comment]
Ok, my fault... I try to use `make html` and the sphynx-generated html pages show correctly the code sections.
When I opened this issue, I was reading the file via browser on Github... so it's a Github's limitation, not an error in the documentation.
Sorry for the stupid warning and for this useless issue =)
